-- Generated by tools/schemagen. Do not edit by hand: change the schema there
-- and run `go generate ./tools/schemagen`.
--
-- The three dialects below say the same thing. Writing them by hand is what
-- eighty migrations of this fork do, and every one of them is a place where
-- somebody has to remember three answers to one question.

{{if .sqlite}}
-- Everybody the board knows: people, and — under their own names and
-- with no column to tell them apart — the agents and the sources.
-- password, mfa_secret, auth_service and auth_data are unused: this
-- application creates every account itself and has no passwords.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}users` (`id` varchar NULL, `username` varchar NULL, `email` varchar NULL, `password` varchar NULL, `mfa_secret` varchar NULL, `auth_service` varchar NULL, `auth_data` varchar NULL, `props` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, PRIMARY KEY (`id`));

-- The team a board belongs to. In this product there is exactly one and
-- its id is '0' — but the column is in two hundred queries of the fork,
-- and working with teams stays as it is.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}teams` (`id` varchar NULL, `signup_token` varchar NOT NULL, `settings` text NULL, `modified_by` varchar NULL, `update_at` bigint NULL, PRIMARY KEY (`id`));

-- A logged-in session. Its token is what proxy.go hands the page.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}sessions` (`id` varchar NULL, `token` varchar NULL, `user_id` varchar NULL, `props` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `auth_service` varchar NULL, PRIMARY KEY (`id`));

-- Key and value, for the handful of things the server records about itself.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}system_settings` (`id` varchar NULL, `value` text NULL, PRIMARY KEY (`id`));

-- A board.
--   channel_id: A remnant of the Mattermost plugin. Nothing writes it.
--   type: O — open, P — private.
--   properties: The board's own automation lives here — xciiiColumns, xciiiFlows,
--     xciiiPrompt and the records of which field is which. JSON on purpose:
--     it travels with the board, into an export and into a template.
--   card_properties: The schema of a card's fields. The product's main denormalisation, and
--     deliberately left alone: the whole webapp filters and groups on it.
CREATE TABLE `{{.prefix}}boards` (`id` varchar NOT NULL, `insert_at` datetime NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')), `team_id` varchar NOT NULL, `channel_id` varchar NULL, `created_by` varchar NULL, `modified_by` varchar NULL, `type` varchar NOT NULL, `title` text NOT NULL, `description` text NULL, `icon` varchar NULL, `show_description` boolean NULL, `is_template` boolean NULL, `template_version` int NULL DEFAULT (0), `properties` text NULL, `card_properties` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, `minimum_role` varchar NOT NULL DEFAULT (''), PRIMARY KEY (`id`));

CREATE INDEX `idx_{{.prefix}}boards_team_id_is_template` ON `{{.prefix}}boards` (`team_id`, `is_template`);

CREATE INDEX `idx_{{.prefix}}boards_channel_id` ON `{{.prefix}}boards` (`channel_id`);

-- Every version of every board, one row per edit, never pruned. The
-- upstream's audit and undo mechanism; this product's undo is in the page
-- (webapp/src/undomanager.ts) and there is no history screen, so whether
-- to keep these three tables at all is a decision worth taking on its
-- own rather than inside a collapse.
--   channel_id: A remnant of the Mattermost plugin. Nothing writes it.
--   type: O — open, P — private.
--   properties: The board's own automation lives here — xciiiColumns, xciiiFlows,
--     xciiiPrompt and the records of which field is which. JSON on purpose:
--     it travels with the board, into an export and into a template.
--   card_properties: The schema of a card's fields. The product's main denormalisation, and
--     deliberately left alone: the whole webapp filters and groups on it.
CREATE TABLE `{{.prefix}}boards_history` (`id` varchar NOT NULL, `insert_at` datetime NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')), `team_id` varchar NOT NULL, `channel_id` varchar NULL, `created_by` varchar NULL, `modified_by` varchar NULL, `type` varchar NOT NULL, `title` text NOT NULL, `description` text NULL, `icon` varchar NULL, `show_description` boolean NULL, `is_template` boolean NULL, `template_version` int NULL DEFAULT (0), `properties` text NULL, `card_properties` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, `minimum_role` varchar NOT NULL DEFAULT (''), PRIMARY KEY (`id`, `insert_at`));

-- Everything on a board: cards, views, comments, text, attachments. A
-- card is a row here with type='card', and it is what every table this
-- application owns points at.
--   id: Nullable, which a primary key makes impossible in practice — but this
--     is what the migrations leave, and reproducing it is the point.
--   parent_id: The tree inside a board: a comment or a text block hangs off a card.
--   schema: A version number for the row's own shape. Backticked by the fork's
--     queries on MySQL, where `schema` is reserved.
--   fields: The card's field values, {property_id: value}.
--   root_id: Always equal to board_id. A remnant.
CREATE TABLE `{{.prefix}}blocks` (`id` varchar NULL, `insert_at` datetime NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')), `parent_id` varchar NULL, `schema` bigint NULL, `type` text NULL, `title` text NULL, `fields` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, `root_id` varchar NULL, `modified_by` varchar NULL, `channel_id` varchar NULL, `created_by` varchar NULL, `board_id` varchar NULL, PRIMARY KEY (`id`));

CREATE INDEX `idx_{{.prefix}}blocks_board_id_parent_id` ON `{{.prefix}}blocks` (`board_id`, `parent_id`);

-- Every version of every block. See boards_history.
--   id: Nullable, which a primary key makes impossible in practice — but this
--     is what the migrations leave, and reproducing it is the point.
--   parent_id: The tree inside a board: a comment or a text block hangs off a card.
--   schema: A version number for the row's own shape. Backticked by the fork's
--     queries on MySQL, where `schema` is reserved.
--   fields: The card's field values, {property_id: value}.
--   root_id: Always equal to board_id. A remnant.
CREATE TABLE `{{.prefix}}blocks_history` (`id` varchar NULL, `insert_at` datetime NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')), `parent_id` varchar NULL, `schema` bigint NULL, `type` text NULL, `title` text NULL, `fields` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, `root_id` varchar NULL, `modified_by` varchar NULL, `channel_id` varchar NULL, `created_by` varchar NULL, `board_id` varchar NULL, PRIMARY KEY (`id`, `insert_at`));

-- Who is on a board, and what they may do there.
CREATE TABLE `{{.prefix}}board_members` (`board_id` varchar NOT NULL, `user_id` varchar NOT NULL, `roles` varchar NULL, `scheme_admin` boolean NULL, `scheme_editor` boolean NULL, `scheme_commenter` boolean NULL, `scheme_viewer` boolean NULL, PRIMARY KEY (`board_id`, `user_id`));

CREATE INDEX `idx_{{.prefix}}board_members_user_id` ON `{{.prefix}}board_members` (`user_id`);

-- Who joined or left a board, and when.
CREATE TABLE `{{.prefix}}board_members_history` (`board_id` varchar NOT NULL, `user_id` varchar NOT NULL, `action` varchar NULL, `insert_at` datetime NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')), PRIMARY KEY (`board_id`, `user_id`, `insert_at`));

CREATE INDEX `idx_{{.prefix}}board_members_history_user_id` ON `{{.prefix}}board_members_history` (`user_id`);

CREATE INDEX `idx_{{.prefix}}board_members_history_board_id_user_id` ON `{{.prefix}}board_members_history` (`board_id`, `user_id`);

-- A group of boards in the sidebar.
CREATE TABLE `{{.prefix}}categories` (`id` varchar NOT NULL, `name` varchar NOT NULL, `user_id` varchar NOT NULL, `team_id` varchar NOT NULL, `channel_id` varchar NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, `collapsed` boolean NULL DEFAULT (false), `type` varchar NULL, `sort_order` bigint NULL, PRIMARY KEY (`id`));

CREATE INDEX `idx_{{.prefix}}categories_user_id_team_id` ON `{{.prefix}}categories` (`user_id`, `team_id`);

-- Which board sits in which sidebar group. The surrogate id is
-- upstream's; the row is really the pair, which the unique index says.
CREATE TABLE `{{.prefix}}category_boards` (`id` varchar NOT NULL, `user_id` varchar NOT NULL, `category_id` varchar NOT NULL, `board_id` varchar NOT NULL, `create_at` bigint NULL, `update_at` bigint NULL, `sort_order` bigint NULL, `hidden` boolean NULL, PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `{{.prefix}}unique_user_category_board` ON `{{.prefix}}category_boards` (`user_id`, `board_id`);

-- A board's public link. The id is the board's, so this is one-to-one.
--   id: Nullable, which the migrations leave and this reproduces.
--   workspace_id: An older remnant than channel_id: workspaces predated teams.
CREATE TABLE `{{.prefix}}sharing` (`id` varchar NULL, `enabled` boolean NULL, `token` varchar NULL, `modified_by` varchar NULL, `update_at` bigint NULL, `workspace_id` varchar NULL, PRIMARY KEY (`id`));

-- An attachment. It has no primary key, which is what the migrations
-- leave: 000041 was where one would have been added, and this is a
-- reproduction rather than a repair.
CREATE TABLE `{{.prefix}}file_info` (`id` varchar NOT NULL, `create_at` bigint NOT NULL, `delete_at` bigint NULL, `name` text NOT NULL, `extension` varchar NOT NULL, `size` bigint NOT NULL, `archived` boolean NULL, `path` varchar NULL);

-- What a person chose, per category and name. Not where this app keeps
-- the page's own settings — those are <dataDir>/ui-settings.json, because
-- the desktop window opens on a fresh origin every launch.
CREATE TABLE `{{.prefix}}preferences` (`userid` varchar NOT NULL, `category` varchar NOT NULL, `name` varchar NOT NULL, `value` text NULL, PRIMARY KEY (`userid`, `category`, `name`));

CREATE INDEX `idx_{{.prefix}}preferences_category` ON `{{.prefix}}preferences` (`category`);

CREATE INDEX `idx_{{.prefix}}preferences_name` ON `{{.prefix}}preferences` (`name`);

-- Who is watching a block, for the notification service.
--   block_id: Nullable, which the migrations leave and this reproduces.
--   subscriber_id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}subscriptions` (`block_type` varchar NULL, `block_id` varchar NULL, `workspace_id` varchar NULL, `subscriber_type` varchar NULL, `subscriber_id` varchar NULL, `notified_at` bigint NULL, `create_at` bigint NULL, `delete_at` bigint NULL, PRIMARY KEY (`block_id`, `subscriber_id`));

CREATE INDEX `idx_{{.prefix}}subscriptions_subscriber_id` ON `{{.prefix}}subscriptions` (`subscriber_id`);

-- A block that has changed and whose watchers have not been told yet.
--   block_id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}notification_hints` (`block_type` varchar NULL, `block_id` varchar NULL, `workspace_id` varchar NULL, `modified_by_id` varchar NULL, `create_at` bigint NULL, `notify_at` bigint NULL, PRIMARY KEY (`block_id`));

-- Network settings several agents share, so they are edited in one
-- place. Was the `proxies` array in config.json.
--   password: Kept apart from the URL so it is entered raw and masked on screen.
--     Still stored in the clear here, exactly as it was in the settings
--     file: moving it into internal/secrets is its own change.
CREATE TABLE `{{.prefix}}proxy` (`id` varchar NOT NULL, `name` varchar NOT NULL, `url` text NULL, `no_proxy` text NULL, `ca_cert` text NULL, `username` varchar NULL, `password` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `idx_{{.prefix}}proxy_name` ON `{{.prefix}}proxy` (`name`);

-- A named place an agent can work in. Was the `projects` array in
-- config.json; a card points at it by id, which is also the id of the
-- board option offered for it, so a card naming its folder is a card
-- holding an ordinary select value that happens to be a reference.
--   name: A caption, not a key. Renaming it breaks nothing, which is the
--     whole reason the id exists.
--   board_id: The board that offers this folder, and the only one that does.
--     NULL means no board has claimed it — a state the product already
--     has a name and a screen for, which is why a deleted board sets this
--     to NULL rather than taking the registry entry with it.
--   global: «На всех досках»: one entry seen from several boards, which is what
--     makes the mode belong to the pair rather than to the folder.
--   kind: What somebody was promised, not what the folder happens to be:
--     'git' means a repository was demanded and one without git is an
--     error. NULL is the ordinary case and means nobody said.
CREATE TABLE `{{.prefix}}workspace` (`id` varchar NOT NULL, `name` varchar NOT NULL, `path` text NULL, `board_id` varchar NULL, `global` boolean NOT NULL, `kind` varchar NULL, `base_branch` varchar NULL, `branch_prefix` varchar NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `workspace_offered_on` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE SET NULL);

CREATE UNIQUE INDEX `idx_{{.prefix}}workspace_name` ON `{{.prefix}}workspace` (`name`);

-- Which board a folder is offered to and how work happens in it there.
-- Keyed by the pair rather than by the folder, because a folder marked
-- «на всех досках» is one entry with a different answer per board: a copy
-- per card where three people work it, a branch in place where one does.
-- Was WorkdirEntry.Modes, a map keyed by board id.
--   mode: worktree | branch. NULL means nobody answered, and the machine's
--     own default stands in.
CREATE TABLE `{{.prefix}}workspace_board` (`workspace_id` varchar NOT NULL, `board_id` varchar NOT NULL, `mode` varchar NULL, PRIMARY KEY (`workspace_id`, `board_id`), CONSTRAINT `workspace_board_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `{{.prefix}}workspace` (`id`) ON DELETE CASCADE, CONSTRAINT `workspace_board_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

-- A registered agent. Its board account is a row in users, and the two
-- are joined by a key rather than by their names happening to match —
-- which is what made renaming an agent break the crew of every route on
-- every board, silently.
--   name: On screen and in the account's username. No longer a reference.
--   user_id: The board account. NULL until one is made, and NULL again if it is
--     deleted: the registry entry is the machine's and outlives it.
--   settings: env, args, cliArgs, options, autoAllowTools, command,
--     terminalCommand, mcpServers. JSON on purpose: this is how to start
--     a process, it points at nothing and nothing joins to it.
CREATE TABLE `{{.prefix}}agent` (`id` varchar NOT NULL, `name` varchar NOT NULL, `kind` varchar NOT NULL, `user_id` varchar NULL, `proxy_id` varchar NULL, `bin_path` text NULL, `model` varchar NULL, `prompt` text NULL, `settings` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `agent_user` FOREIGN KEY (`user_id`) REFERENCES `{{.prefix}}users` (`id`) ON DELETE SET NULL, CONSTRAINT `agent_proxy` FOREIGN KEY (`proxy_id`) REFERENCES `{{.prefix}}proxy` (`id`) ON DELETE SET NULL);

CREATE UNIQUE INDEX `idx_{{.prefix}}agent_name` ON `{{.prefix}}agent` (`name`);

-- Where a card's branch is published. Was the `deploys` array in
-- config.json, and a route's stage named it by name.
CREATE TABLE `{{.prefix}}deploy_target` (`id` varchar NOT NULL, `name` varchar NOT NULL, `ssh_host` varchar NOT NULL, `ssh_user` varchar NULL, `ssh_port` bigint NULL, `ssh_key` text NULL, `base_app` varchar NULL, `base_domain` varchar NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `idx_{{.prefix}}deploy_target_name` ON `{{.prefix}}deploy_target` (`name`);

-- A run of an agent over ACP. One process, one verdict: unlike a
-- conversation, it is never resumed, which is why the two are
-- separate tables and not one row with a transport column.
--   card_id: NULL for a run that is about no card — naming a branch is one.
--   finished_at: NULL means the session is still live.
CREATE TABLE `{{.prefix}}agent_session` (`id` varchar NOT NULL, `card_id` varchar NULL, `board_id` varchar NULL, `agent_kind` varchar NOT NULL, `acp_session_id` varchar NULL, `status` varchar NOT NULL, `cwd` text NULL, `worktree_path` text NULL, `branch` varchar NULL, `started_at` bigint NOT NULL, `finished_at` bigint NULL, `error_text` text NULL, PRIMARY KEY (`id`), CONSTRAINT `agent_session_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `agent_session_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

CREATE INDEX `idx_{{.prefix}}agent_session_card` ON `{{.prefix}}agent_session` (`card_id`, `started_at`);

-- What happened during a session, in order. The id is a UUIDv7 rather
-- than an autoincrement: v7 sorts by time, so ORDER BY id still means
-- "as it happened" and the three spellings of AUTO_INCREMENT are gone.
-- `seq` went with them — it was the same fact told twice.
CREATE TABLE `{{.prefix}}session_event` (`id` varchar NOT NULL, `session_id` varchar NOT NULL, `kind` varchar NOT NULL, `payload_json` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `session_event_session` FOREIGN KEY (`session_id`) REFERENCES `{{.prefix}}agent_session` (`id`) ON DELETE CASCADE);

CREATE INDEX `idx_{{.prefix}}session_event_session` ON `{{.prefix}}session_event` (`session_id`, `id`);

-- A conversation with an agent: its CLI in a pty, keyed (card, node).
-- The row outlives every process that ever drew it — that is what makes
-- a conversation resumable, and it is the difference from agent_session,
-- which is one run and then over.
--   card_id: NULL for a planning conversation: it is about no card.
--   node_id: The column's option id — work; '@talk' — discussion; '@none' — a
--     card with no column at all.
--   column_name: What the column was called at the time, frozen: the option may be
--     gone, and the row still has to read the same.
--   summary: The agent's own line about what this conversation is doing.
--   workdir_path: Was repo_path. Becomes workspace_id in the second half of step 2,
--     together with the code that resolves a folder to its registry id.
CREATE TABLE `{{.prefix}}conversation` (`id` varchar NOT NULL, `card_id` varchar NULL, `board_id` varchar NULL, `node_id` varchar NOT NULL, `column_name` varchar NULL, `title` text NULL, `summary` text NULL, `agent` varchar NULL, `kind` varchar NULL, `workdir_path` text NULL, `cwd` text NULL, `branch` varchar NULL, `started_at` bigint NOT NULL, `ended_at` bigint NULL, `exit_code` bigint NULL, PRIMARY KEY (`id`), CONSTRAINT `conversation_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `conversation_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

CREATE INDEX `idx_{{.prefix}}conversation_card` ON `{{.prefix}}conversation` (`card_id`, `started_at`);

CREATE INDEX `idx_{{.prefix}}conversation_card_node` ON `{{.prefix}}conversation` (`card_id`, `node_id`, `started_at`);

-- One route event, handled once. `key` was the column's name and is a
-- reserved word in MySQL, so it is `token` — cheaper than backticks in
-- every query for ever.
CREATE TABLE `{{.prefix}}idempotency` (`token` varchar NOT NULL, `session_id` varchar NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`token`));

CREATE INDEX `idx_{{.prefix}}idempotency_created` ON `{{.prefix}}idempotency` (`created_at`);

-- This machine's index of where each card is on its route. The truth is
-- on the card itself, so it travels with the board; this is what the VCS
-- watcher asks "which cards are parked and on what branch" in one query.
--   flow: The route's name. It has no id of its own yet — contradiction 4 of
--     docs/model-graph.md, which lives inside the board's JSON.
CREATE TABLE `{{.prefix}}flow_state` (`card_id` varchar NOT NULL, `board_id` varchar NULL, `flow` varchar NOT NULL, `node_id` varchar NOT NULL, `branch` varchar NULL, `workdir_path` text NULL, `entered_at` bigint NOT NULL, PRIMARY KEY (`card_id`), CONSTRAINT `flow_state_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `flow_state_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

-- Every transition a card made, and what the agent said on it.
--   said: The agent's closing words: what a conversation is told instead of
--     its task when the card comes back to it.
CREATE TABLE `{{.prefix}}flow_event` (`id` varchar NOT NULL, `card_id` varchar NOT NULL, `flow` varchar NOT NULL, `from_node` varchar NULL, `to_node` varchar NOT NULL, `on_kind` varchar NOT NULL, `detail` text NULL, `said` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `flow_event_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE);

CREATE INDEX `idx_{{.prefix}}flow_event_card` ON `{{.prefix}}flow_event` (`card_id`, `id`);

-- One current reason a card is not moving — not a journal. The reason is
-- true only until somebody fixes what it is about, and a comment would
-- outlive it as noise.
--   kind: 'conversation' is the one kind with somewhere to go: open the
--     terminal. The rest have no button, which is why this is a field and
--     never a reading of the reason's own Russian.
CREATE TABLE `{{.prefix}}card_stall` (`card_id` varchar NOT NULL, `node_id` varchar NULL, `kind` varchar NULL, `reason` text NOT NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`card_id`), CONSTRAINT `card_stall_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE);

-- A card waiting for its column to free up a place.
--   column_key: board|option — the queue belongs to one column of one board.
CREATE TABLE `{{.prefix}}stage_queue` (`card_id` varchar NOT NULL, `board_id` varchar NULL, `column_key` varchar NOT NULL, `flow` varchar NULL, `node_id` varchar NULL, `queued_at` bigint NOT NULL, PRIMARY KEY (`card_id`), CONSTRAINT `stage_queue_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `stage_queue_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

CREATE INDEX `idx_{{.prefix}}stage_queue_column` ON `{{.prefix}}stage_queue` (`column_key`, `queued_at`);

-- Which setup questions a board has been asked. It is about this machine
-- — the answers are folders and hosts here — so it cannot live in the
-- browser's storage, which the desktop window forgets on every launch.
--   changed_at: Was `at`. AT is a keyword in Postgres and a name not worth having.
CREATE TABLE `{{.prefix}}board_setup` (`board_id` varchar NOT NULL, `step` varchar NOT NULL, `status` varchar NOT NULL, `changed_at` bigint NOT NULL, PRIMARY KEY (`board_id`, `step`), CONSTRAINT `board_setup_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

-- This branch event has already been acted on. Keyed by the workspace
-- rather than by its path: a folder somebody moved used to keep its
-- latches, and MySQL would refuse a path in a key of any real length.
--   marker: The commit the event refers to: the same state seen twice fires once.
CREATE TABLE `{{.prefix}}vcs_seen` (`workspace_id` varchar NOT NULL, `branch` varchar NOT NULL, `kind` varchar NOT NULL, `marker` varchar NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`workspace_id`, `branch`, `kind`), CONSTRAINT `vcs_seen_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `{{.prefix}}workspace` (`id`) ON DELETE CASCADE);

-- The directory and the branch one owner holds in one workspace. The
-- owner is a card, or a board for a conversation with no card — two
-- nullable columns rather than one string, because a foreign key cannot
-- point at two tables through one.
--   id: A surrogate, and the one place in this schema where that is right:
--     the natural key would have to include a nullable column, which MySQL
--     and Postgres forbid in a primary key. Uniqueness is stated in the
--     indexes below instead, where a NULL is allowed to differ from a NULL.
--     Nothing outside this application creates a checkout, so no client has
--     to be able to supply the id.
--   board_id: Set for «черновики доски»: a conversation with no card still works
--     somewhere, and that somewhere belongs to the board.
--   path: Where the copy is. Not the workspace's own path — that is on the
--     workspace, and this is the worktree cut from it.
--   base: What the branch was cut from, and therefore what «merged» means.
--   released_at: NULL means the checkout is live.
CREATE TABLE `{{.prefix}}checkout` (`id` varchar NOT NULL, `workspace_id` varchar NOT NULL, `card_id` varchar NULL, `board_id` varchar NULL, `mode` varchar NOT NULL, `branch` varchar NULL, `path` text NULL, `base` varchar NULL, `created_at` bigint NOT NULL, `released_at` bigint NULL, PRIMARY KEY (`id`), CONSTRAINT `checkout_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `{{.prefix}}workspace` (`id`) ON DELETE RESTRICT, CONSTRAINT `checkout_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `checkout_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

CREATE UNIQUE INDEX `idx_{{.prefix}}checkout_card` ON `{{.prefix}}checkout` (`workspace_id`, `card_id`);

CREATE UNIQUE INDEX `idx_{{.prefix}}checkout_board` ON `{{.prefix}}checkout` (`workspace_id`, `board_id`);

CREATE INDEX `idx_{{.prefix}}checkout_live` ON `{{.prefix}}checkout` (`workspace_id`, `released_at`);

-- What a source has already brought. The same letter arriving twice adds
-- to the card it made rather than making a second one.
--   version: The service's own updated/etag: changed means there is something
--     to add.
CREATE TABLE `{{.prefix}}source_item` (`source` varchar NOT NULL, `external_id` varchar NOT NULL, `version` varchar NULL, `card_id` varchar NULL, `created_at` bigint NOT NULL, `updated_at` bigint NOT NULL, PRIMARY KEY (`source`, `external_id`), CONSTRAINT `source_item_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE SET NULL);

CREATE INDEX `idx_{{.prefix}}source_item_card` ON `{{.prefix}}source_item` (`card_id`);

-- Why nothing happened — the only question anybody asks of a source.
-- Deleting the card it produced does not delete the line: what a source
-- decided is a fact about the source.
CREATE TABLE `{{.prefix}}source_event` (`id` varchar NOT NULL, `source` varchar NOT NULL, `external_id` varchar NULL, `rule` varchar NULL, `outcome` varchar NOT NULL, `card_id` varchar NULL, `detail` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `source_event_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE SET NULL);

CREATE INDEX `idx_{{.prefix}}source_event_source` ON `{{.prefix}}source_event` (`source`, `id`);
{{end}}

{{if .mysql}}
-- A block that has changed and whose watchers have not been told yet.
--   block_id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}notification_hints` (`block_type` varchar(10) NULL, `block_id` varchar(36) NULL, `workspace_id` varchar(36) NULL, `modified_by_id` varchar(36) NULL, `create_at` bigint NULL, `notify_at` bigint NULL, PRIMARY KEY (`block_id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- One route event, handled once. `key` was the column's name and is a
-- reserved word in MySQL, so it is `token` — cheaper than backticks in
-- every query for ever.
CREATE TABLE `{{.prefix}}idempotency` (`token` varchar(255) NOT NULL, `session_id` varchar(36) NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`token`), INDEX `idx_{{.prefix}}idempotency_created` (`created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A logged-in session. Its token is what proxy.go hands the page.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}sessions` (`id` varchar(100) NULL, `token` varchar(100) NULL, `user_id` varchar(100) NULL, `props` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `auth_service` varchar(20) NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Key and value, for the handful of things the server records about itself.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}system_settings` (`id` varchar(100) NULL, `value` text NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Everybody the board knows: people, and — under their own names and
-- with no column to tell them apart — the agents and the sources.
-- password, mfa_secret, auth_service and auth_data are unused: this
-- application creates every account itself and has no passwords.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}users` (`id` varchar(100) NULL, `username` varchar(100) NULL, `email` varchar(255) NULL, `password` varchar(100) NULL, `mfa_secret` varchar(100) NULL, `auth_service` varchar(20) NULL, `auth_data` varchar(255) NULL, `props` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Every version of every board, one row per edit, never pruned. The
-- upstream's audit and undo mechanism; this product's undo is in the page
-- (webapp/src/undomanager.ts) and there is no history screen, so whether
-- to keep these three tables at all is a decision worth taking on its
-- own rather than inside a collapse.
--   channel_id: A remnant of the Mattermost plugin. Nothing writes it.
--   type: O — open, P — private.
--   properties: The board's own automation lives here — xciiiColumns, xciiiFlows,
--     xciiiPrompt and the records of which field is which. JSON on purpose:
--     it travels with the board, into an export and into a template.
--   card_properties: The schema of a card's fields. The product's main denormalisation, and
--     deliberately left alone: the whole webapp filters and groups on it.
CREATE TABLE `{{.prefix}}boards_history` (`id` varchar(36) NOT NULL, `insert_at` datetime(6) NOT NULL DEFAULT "NOW(6)", `team_id` varchar(36) NOT NULL, `channel_id` varchar(36) NULL, `created_by` varchar(36) NULL, `modified_by` varchar(36) NULL, `type` varchar(1) NOT NULL, `title` text NOT NULL, `description` text NULL, `icon` varchar(256) NULL, `show_description` bool NULL, `is_template` bool NULL, `template_version` int NULL DEFAULT 0, `properties` text NULL, `card_properties` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, `minimum_role` varchar(36) NOT NULL DEFAULT '', PRIMARY KEY (`id`, `insert_at`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Where a card's branch is published. Was the `deploys` array in
-- config.json, and a route's stage named it by name.
CREATE TABLE `{{.prefix}}deploy_target` (`id` varchar(36) NOT NULL, `name` varchar(100) NOT NULL, `ssh_host` varchar(255) NOT NULL, `ssh_user` varchar(64) NULL, `ssh_port` bigint NULL, `ssh_key` text NULL, `base_app` varchar(100) NULL, `base_domain` varchar(255) NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idx_{{.prefix}}deploy_target_name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Every version of every block. See boards_history.
--   id: Nullable, which a primary key makes impossible in practice — but this
--     is what the migrations leave, and reproducing it is the point.
--   parent_id: The tree inside a board: a comment or a text block hangs off a card.
--   schema: A version number for the row's own shape. Backticked by the fork's
--     queries on MySQL, where `schema` is reserved.
--   fields: The card's field values, {property_id: value}.
--   root_id: Always equal to board_id. A remnant.
CREATE TABLE `{{.prefix}}blocks_history` (`id` varchar(36) NULL, `insert_at` datetime(6) NOT NULL DEFAULT "NOW(6)", `parent_id` varchar(36) NULL, `schema` bigint NULL, `type` text NULL, `title` text NULL, `fields` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, `root_id` varchar(36) NULL, `modified_by` varchar(36) NULL, `channel_id` varchar(36) NULL, `created_by` varchar(36) NULL, `board_id` varchar(36) NULL, PRIMARY KEY (`id`, `insert_at`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Who is on a board, and what they may do there.
CREATE TABLE `{{.prefix}}board_members` (`board_id` varchar(36) NOT NULL, `user_id` varchar(36) NOT NULL, `roles` varchar(64) NULL, `scheme_admin` bool NULL, `scheme_editor` bool NULL, `scheme_commenter` bool NULL, `scheme_viewer` bool NULL, PRIMARY KEY (`board_id`, `user_id`), INDEX `idx_{{.prefix}}board_members_user_id` (`user_id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Who joined or left a board, and when.
CREATE TABLE `{{.prefix}}board_members_history` (`board_id` varchar(36) NOT NULL, `user_id` varchar(36) NOT NULL, `action` varchar(10) NULL, `insert_at` datetime(6) NOT NULL DEFAULT "NOW(6)", PRIMARY KEY (`board_id`, `user_id`, `insert_at`), INDEX `idx_{{.prefix}}board_members_history_user_id` (`user_id`), INDEX `idx_{{.prefix}}board_members_history_board_id_user_id` (`board_id`, `user_id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A group of boards in the sidebar.
CREATE TABLE `{{.prefix}}categories` (`id` varchar(36) NOT NULL, `name` varchar(100) NOT NULL, `user_id` varchar(36) NOT NULL, `team_id` varchar(36) NOT NULL, `channel_id` varchar(36) NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, `collapsed` bool NULL DEFAULT false, `type` varchar(64) NULL, `sort_order` bigint NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}categories_user_id_team_id` (`user_id`, `team_id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Which board sits in which sidebar group. The surrogate id is
-- upstream's; the row is really the pair, which the unique index says.
CREATE TABLE `{{.prefix}}category_boards` (`id` varchar(36) NOT NULL, `user_id` varchar(36) NOT NULL, `category_id` varchar(36) NOT NULL, `board_id` varchar(36) NOT NULL, `create_at` bigint NULL, `update_at` bigint NULL, `sort_order` bigint NULL, `hidden` bool NULL, PRIMARY KEY (`id`), UNIQUE INDEX `{{.prefix}}unique_user_category_board` (`user_id`, `board_id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A board's public link. The id is the board's, so this is one-to-one.
--   id: Nullable, which the migrations leave and this reproduces.
--   workspace_id: An older remnant than channel_id: workspaces predated teams.
CREATE TABLE `{{.prefix}}sharing` (`id` varchar(36) NULL, `enabled` bool NULL, `token` varchar(100) NULL, `modified_by` varchar(36) NULL, `update_at` bigint NULL, `workspace_id` varchar(36) NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- An attachment. It has no primary key, which is what the migrations
-- leave: 000041 was where one would have been added, and this is a
-- reproduction rather than a repair.
CREATE TABLE `{{.prefix}}file_info` (`id` varchar(26) NOT NULL, `create_at` bigint NOT NULL, `delete_at` bigint NULL, `name` text NOT NULL, `extension` varchar(50) NOT NULL, `size` bigint NOT NULL, `archived` bool NULL, `path` varchar(512) NULL) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- What a person chose, per category and name. Not where this app keeps
-- the page's own settings — those are <dataDir>/ui-settings.json, because
-- the desktop window opens on a fresh origin every launch.
CREATE TABLE `{{.prefix}}preferences` (`userid` varchar(36) NOT NULL, `category` varchar(32) NOT NULL, `name` varchar(32) NOT NULL, `value` text NULL, PRIMARY KEY (`userid`, `category`, `name`), INDEX `idx_{{.prefix}}preferences_category` (`category`), INDEX `idx_{{.prefix}}preferences_name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Who is watching a block, for the notification service.
--   block_id: Nullable, which the migrations leave and this reproduces.
--   subscriber_id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}subscriptions` (`block_type` varchar(10) NULL, `block_id` varchar(36) NULL, `workspace_id` varchar(36) NULL, `subscriber_type` varchar(10) NULL, `subscriber_id` varchar(36) NULL, `notified_at` bigint NULL, `create_at` bigint NULL, `delete_at` bigint NULL, PRIMARY KEY (`block_id`, `subscriber_id`), INDEX `idx_{{.prefix}}subscriptions_subscriber_id` (`subscriber_id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- The team a board belongs to. In this product there is exactly one and
-- its id is '0' — but the column is in two hundred queries of the fork,
-- and working with teams stays as it is.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE `{{.prefix}}teams` (`id` varchar(36) NULL, `signup_token` varchar(100) NOT NULL, `settings` text NULL, `modified_by` varchar(36) NULL, `update_at` bigint NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Network settings several agents share, so they are edited in one
-- place. Was the `proxies` array in config.json.
--   password: Kept apart from the URL so it is entered raw and masked on screen.
--     Still stored in the clear here, exactly as it was in the settings
--     file: moving it into internal/secrets is its own change.
CREATE TABLE `{{.prefix}}proxy` (`id` varchar(36) NOT NULL, `name` varchar(100) NOT NULL, `url` text NULL, `no_proxy` text NULL, `ca_cert` text NULL, `username` varchar(100) NULL, `password` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idx_{{.prefix}}proxy_name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A registered agent. Its board account is a row in users, and the two
-- are joined by a key rather than by their names happening to match —
-- which is what made renaming an agent break the crew of every route on
-- every board, silently.
--   name: On screen and in the account's username. No longer a reference.
--   user_id: The board account. NULL until one is made, and NULL again if it is
--     deleted: the registry entry is the machine's and outlives it.
--   settings: env, args, cliArgs, options, autoAllowTools, command,
--     terminalCommand, mcpServers. JSON on purpose: this is how to start
--     a process, it points at nothing and nothing joins to it.
CREATE TABLE `{{.prefix}}agent` (`id` varchar(36) NOT NULL, `name` varchar(100) NOT NULL, `kind` varchar(32) NOT NULL, `user_id` varchar(36) NULL, `proxy_id` varchar(36) NULL, `bin_path` text NULL, `model` varchar(100) NULL, `prompt` text NULL, `settings` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idx_{{.prefix}}agent_name` (`name`), CONSTRAINT `agent_user` FOREIGN KEY (`user_id`) REFERENCES `{{.prefix}}users` (`id`) ON DELETE SET NULL, CONSTRAINT `agent_proxy` FOREIGN KEY (`proxy_id`) REFERENCES `{{.prefix}}proxy` (`id`) ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Everything on a board: cards, views, comments, text, attachments. A
-- card is a row here with type='card', and it is what every table this
-- application owns points at.
--   id: Nullable, which a primary key makes impossible in practice — but this
--     is what the migrations leave, and reproducing it is the point.
--   parent_id: The tree inside a board: a comment or a text block hangs off a card.
--   schema: A version number for the row's own shape. Backticked by the fork's
--     queries on MySQL, where `schema` is reserved.
--   fields: The card's field values, {property_id: value}.
--   root_id: Always equal to board_id. A remnant.
CREATE TABLE `{{.prefix}}blocks` (`id` varchar(36) NULL, `insert_at` datetime(6) NOT NULL DEFAULT "NOW(6)", `parent_id` varchar(36) NULL, `schema` bigint NULL, `type` text NULL, `title` text NULL, `fields` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, `root_id` varchar(36) NULL, `modified_by` varchar(36) NULL, `channel_id` varchar(36) NULL, `created_by` varchar(36) NULL, `board_id` varchar(36) NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}blocks_board_id_parent_id` (`board_id`, `parent_id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A board.
--   channel_id: A remnant of the Mattermost plugin. Nothing writes it.
--   type: O — open, P — private.
--   properties: The board's own automation lives here — xciiiColumns, xciiiFlows,
--     xciiiPrompt and the records of which field is which. JSON on purpose:
--     it travels with the board, into an export and into a template.
--   card_properties: The schema of a card's fields. The product's main denormalisation, and
--     deliberately left alone: the whole webapp filters and groups on it.
CREATE TABLE `{{.prefix}}boards` (`id` varchar(36) NOT NULL, `insert_at` datetime(6) NOT NULL DEFAULT "NOW(6)", `team_id` varchar(36) NOT NULL, `channel_id` varchar(36) NULL, `created_by` varchar(36) NULL, `modified_by` varchar(36) NULL, `type` varchar(1) NOT NULL, `title` text NOT NULL, `description` text NULL, `icon` varchar(256) NULL, `show_description` bool NULL, `is_template` bool NULL, `template_version` int NULL DEFAULT 0, `properties` text NULL, `card_properties` text NULL, `create_at` bigint NULL, `update_at` bigint NULL, `delete_at` bigint NULL, `minimum_role` varchar(36) NOT NULL DEFAULT '', PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}boards_team_id_is_template` (`team_id`, `is_template`), INDEX `idx_{{.prefix}}boards_channel_id` (`channel_id`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A run of an agent over ACP. One process, one verdict: unlike a
-- conversation, it is never resumed, which is why the two are
-- separate tables and not one row with a transport column.
--   card_id: NULL for a run that is about no card — naming a branch is one.
--   finished_at: NULL means the session is still live.
CREATE TABLE `{{.prefix}}agent_session` (`id` varchar(36) NOT NULL, `card_id` varchar(36) NULL, `board_id` varchar(36) NULL, `agent_kind` varchar(32) NOT NULL, `acp_session_id` varchar(100) NULL, `status` varchar(24) NOT NULL, `cwd` text NULL, `worktree_path` text NULL, `branch` varchar(255) NULL, `started_at` bigint NOT NULL, `finished_at` bigint NULL, `error_text` text NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}agent_session_card` (`card_id`, `started_at`), CONSTRAINT `agent_session_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `agent_session_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Which setup questions a board has been asked. It is about this machine
-- — the answers are folders and hosts here — so it cannot live in the
-- browser's storage, which the desktop window forgets on every launch.
--   changed_at: Was `at`. AT is a keyword in Postgres and a name not worth having.
CREATE TABLE `{{.prefix}}board_setup` (`board_id` varchar(36) NOT NULL, `step` varchar(32) NOT NULL, `status` varchar(16) NOT NULL, `changed_at` bigint NOT NULL, PRIMARY KEY (`board_id`, `step`), CONSTRAINT `board_setup_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- One current reason a card is not moving — not a journal. The reason is
-- true only until somebody fixes what it is about, and a comment would
-- outlive it as noise.
--   kind: 'conversation' is the one kind with somewhere to go: open the
--     terminal. The rest have no button, which is why this is a field and
--     never a reading of the reason's own Russian.
CREATE TABLE `{{.prefix}}card_stall` (`card_id` varchar(36) NOT NULL, `node_id` varchar(64) NULL, `kind` varchar(32) NULL, `reason` text NOT NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`card_id`), CONSTRAINT `card_stall_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A named place an agent can work in. Was the `projects` array in
-- config.json; a card points at it by id, which is also the id of the
-- board option offered for it, so a card naming its folder is a card
-- holding an ordinary select value that happens to be a reference.
--   name: A caption, not a key. Renaming it breaks nothing, which is the
--     whole reason the id exists.
--   board_id: The board that offers this folder, and the only one that does.
--     NULL means no board has claimed it — a state the product already
--     has a name and a screen for, which is why a deleted board sets this
--     to NULL rather than taking the registry entry with it.
--   global: «На всех досках»: one entry seen from several boards, which is what
--     makes the mode belong to the pair rather than to the folder.
--   kind: What somebody was promised, not what the folder happens to be:
--     'git' means a repository was demanded and one without git is an
--     error. NULL is the ordinary case and means nobody said.
CREATE TABLE `{{.prefix}}workspace` (`id` varchar(36) NOT NULL, `name` varchar(200) NOT NULL, `path` text NULL, `board_id` varchar(36) NULL, `global` bool NOT NULL, `kind` varchar(16) NULL, `base_branch` varchar(200) NULL, `branch_prefix` varchar(64) NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idx_{{.prefix}}workspace_name` (`name`), CONSTRAINT `workspace_offered_on` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- The directory and the branch one owner holds in one workspace. The
-- owner is a card, or a board for a conversation with no card — two
-- nullable columns rather than one string, because a foreign key cannot
-- point at two tables through one.
--   id: A surrogate, and the one place in this schema where that is right:
--     the natural key would have to include a nullable column, which MySQL
--     and Postgres forbid in a primary key. Uniqueness is stated in the
--     indexes below instead, where a NULL is allowed to differ from a NULL.
--     Nothing outside this application creates a checkout, so no client has
--     to be able to supply the id.
--   board_id: Set for «черновики доски»: a conversation with no card still works
--     somewhere, and that somewhere belongs to the board.
--   path: Where the copy is. Not the workspace's own path — that is on the
--     workspace, and this is the worktree cut from it.
--   base: What the branch was cut from, and therefore what «merged» means.
--   released_at: NULL means the checkout is live.
CREATE TABLE `{{.prefix}}checkout` (`id` varchar(36) NOT NULL, `workspace_id` varchar(36) NOT NULL, `card_id` varchar(36) NULL, `board_id` varchar(36) NULL, `mode` varchar(16) NOT NULL, `branch` varchar(255) NULL, `path` text NULL, `base` varchar(255) NULL, `created_at` bigint NOT NULL, `released_at` bigint NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idx_{{.prefix}}checkout_card` (`workspace_id`, `card_id`), UNIQUE INDEX `idx_{{.prefix}}checkout_board` (`workspace_id`, `board_id`), INDEX `idx_{{.prefix}}checkout_live` (`workspace_id`, `released_at`), CONSTRAINT `checkout_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `{{.prefix}}workspace` (`id`) ON DELETE RESTRICT, CONSTRAINT `checkout_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `checkout_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A conversation with an agent: its CLI in a pty, keyed (card, node).
-- The row outlives every process that ever drew it — that is what makes
-- a conversation resumable, and it is the difference from agent_session,
-- which is one run and then over.
--   card_id: NULL for a planning conversation: it is about no card.
--   node_id: The column's option id — work; '@talk' — discussion; '@none' — a
--     card with no column at all.
--   column_name: What the column was called at the time, frozen: the option may be
--     gone, and the row still has to read the same.
--   summary: The agent's own line about what this conversation is doing.
--   workdir_path: Was repo_path. Becomes workspace_id in the second half of step 2,
--     together with the code that resolves a folder to its registry id.
CREATE TABLE `{{.prefix}}conversation` (`id` varchar(36) NOT NULL, `card_id` varchar(36) NULL, `board_id` varchar(36) NULL, `node_id` varchar(64) NOT NULL, `column_name` varchar(200) NULL, `title` text NULL, `summary` text NULL, `agent` varchar(100) NULL, `kind` varchar(32) NULL, `workdir_path` text NULL, `cwd` text NULL, `branch` varchar(255) NULL, `started_at` bigint NOT NULL, `ended_at` bigint NULL, `exit_code` bigint NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}conversation_card` (`card_id`, `started_at`), INDEX `idx_{{.prefix}}conversation_card_node` (`card_id`, `node_id`, `started_at`), CONSTRAINT `conversation_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `conversation_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Every transition a card made, and what the agent said on it.
--   said: The agent's closing words: what a conversation is told instead of
--     its task when the card comes back to it.
CREATE TABLE `{{.prefix}}flow_event` (`id` varchar(36) NOT NULL, `card_id` varchar(36) NOT NULL, `flow` varchar(200) NOT NULL, `from_node` varchar(64) NULL, `to_node` varchar(64) NOT NULL, `on_kind` varchar(32) NOT NULL, `detail` text NULL, `said` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}flow_event_card` (`card_id`, `id`), CONSTRAINT `flow_event_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- This machine's index of where each card is on its route. The truth is
-- on the card itself, so it travels with the board; this is what the VCS
-- watcher asks "which cards are parked and on what branch" in one query.
--   flow: The route's name. It has no id of its own yet — contradiction 4 of
--     docs/model-graph.md, which lives inside the board's JSON.
CREATE TABLE `{{.prefix}}flow_state` (`card_id` varchar(36) NOT NULL, `board_id` varchar(36) NULL, `flow` varchar(200) NOT NULL, `node_id` varchar(64) NOT NULL, `branch` varchar(255) NULL, `workdir_path` text NULL, `entered_at` bigint NOT NULL, PRIMARY KEY (`card_id`), CONSTRAINT `flow_state_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `flow_state_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- What happened during a session, in order. The id is a UUIDv7 rather
-- than an autoincrement: v7 sorts by time, so ORDER BY id still means
-- "as it happened" and the three spellings of AUTO_INCREMENT are gone.
-- `seq` went with them — it was the same fact told twice.
CREATE TABLE `{{.prefix}}session_event` (`id` varchar(36) NOT NULL, `session_id` varchar(36) NOT NULL, `kind` varchar(32) NOT NULL, `payload_json` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}session_event_session` (`session_id`, `id`), CONSTRAINT `session_event_session` FOREIGN KEY (`session_id`) REFERENCES `{{.prefix}}agent_session` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Why nothing happened — the only question anybody asks of a source.
-- Deleting the card it produced does not delete the line: what a source
-- decided is a fact about the source.
CREATE TABLE `{{.prefix}}source_event` (`id` varchar(36) NOT NULL, `source` varchar(100) NOT NULL, `external_id` varchar(255) NULL, `rule` varchar(100) NULL, `outcome` varchar(16) NOT NULL, `card_id` varchar(36) NULL, `detail` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}source_event_source` (`source`, `id`), CONSTRAINT `source_event_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- What a source has already brought. The same letter arriving twice adds
-- to the card it made rather than making a second one.
--   version: The service's own updated/etag: changed means there is something
--     to add.
CREATE TABLE `{{.prefix}}source_item` (`source` varchar(100) NOT NULL, `external_id` varchar(255) NOT NULL, `version` varchar(255) NULL, `card_id` varchar(36) NULL, `created_at` bigint NOT NULL, `updated_at` bigint NOT NULL, PRIMARY KEY (`source`, `external_id`), INDEX `idx_{{.prefix}}source_item_card` (`card_id`), CONSTRAINT `source_item_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A card waiting for its column to free up a place.
--   column_key: board|option — the queue belongs to one column of one board.
CREATE TABLE `{{.prefix}}stage_queue` (`card_id` varchar(36) NOT NULL, `board_id` varchar(36) NULL, `column_key` varchar(128) NOT NULL, `flow` varchar(200) NULL, `node_id` varchar(64) NULL, `queued_at` bigint NOT NULL, PRIMARY KEY (`card_id`), INDEX `idx_{{.prefix}}stage_queue_column` (`column_key`, `queued_at`), CONSTRAINT `stage_queue_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `stage_queue_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- This branch event has already been acted on. Keyed by the workspace
-- rather than by its path: a folder somebody moved used to keep its
-- latches, and MySQL would refuse a path in a key of any real length.
--   marker: The commit the event refers to: the same state seen twice fires once.
CREATE TABLE `{{.prefix}}vcs_seen` (`workspace_id` varchar(36) NOT NULL, `branch` varchar(255) NOT NULL, `kind` varchar(32) NOT NULL, `marker` varchar(64) NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`workspace_id`, `branch`, `kind`), CONSTRAINT `vcs_seen_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `{{.prefix}}workspace` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Which board a folder is offered to and how work happens in it there.
-- Keyed by the pair rather than by the folder, because a folder marked
-- «на всех досках» is one entry with a different answer per board: a copy
-- per card where three people work it, a branch in place where one does.
-- Was WorkdirEntry.Modes, a map keyed by board id.
--   mode: worktree | branch. NULL means nobody answered, and the machine's
--     own default stands in.
CREATE TABLE `{{.prefix}}workspace_board` (`workspace_id` varchar(36) NOT NULL, `board_id` varchar(36) NOT NULL, `mode` varchar(16) NULL, PRIMARY KEY (`workspace_id`, `board_id`), CONSTRAINT `workspace_board_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `{{.prefix}}workspace` (`id`) ON DELETE CASCADE, CONSTRAINT `workspace_board_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
{{end}}

{{if .postgres}}
-- A block that has changed and whose watchers have not been told yet.
--   block_id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE "{{.prefix}}notification_hints" ("block_type" character varying(10) NULL, "block_id" character varying(36) NULL, "workspace_id" character varying(36) NULL, "modified_by_id" character varying(36) NULL, "create_at" bigint NULL, "notify_at" bigint NULL, PRIMARY KEY ("block_id"));

-- One route event, handled once. `key` was the column's name and is a
-- reserved word in MySQL, so it is `token` — cheaper than backticks in
-- every query for ever.
CREATE TABLE "{{.prefix}}idempotency" ("token" character varying(255) NOT NULL, "session_id" character varying(36) NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("token"));

-- One route event, handled once. `key` was the column's name and is a
-- reserved word in MySQL, so it is `token` — cheaper than backticks in
-- every query for ever.
CREATE INDEX "idx_{{.prefix}}idempotency_created" ON "{{.prefix}}idempotency" ("created_at");

-- A logged-in session. Its token is what proxy.go hands the page.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE "{{.prefix}}sessions" ("id" character varying(100) NULL, "token" character varying(100) NULL, "user_id" character varying(100) NULL, "props" text NULL, "create_at" bigint NULL, "update_at" bigint NULL, "auth_service" character varying(20) NULL, PRIMARY KEY ("id"));

-- Key and value, for the handful of things the server records about itself.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE "{{.prefix}}system_settings" ("id" character varying(100) NULL, "value" text NULL, PRIMARY KEY ("id"));

-- Everybody the board knows: people, and — under their own names and
-- with no column to tell them apart — the agents and the sources.
-- password, mfa_secret, auth_service and auth_data are unused: this
-- application creates every account itself and has no passwords.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE "{{.prefix}}users" ("id" character varying(100) NULL, "username" character varying(100) NULL, "email" character varying(255) NULL, "password" character varying(100) NULL, "mfa_secret" character varying(100) NULL, "auth_service" character varying(20) NULL, "auth_data" character varying(255) NULL, "props" text NULL, "create_at" bigint NULL, "update_at" bigint NULL, "delete_at" bigint NULL, PRIMARY KEY ("id"));

-- Every version of every board, one row per edit, never pruned. The
-- upstream's audit and undo mechanism; this product's undo is in the page
-- (webapp/src/undomanager.ts) and there is no history screen, so whether
-- to keep these three tables at all is a decision worth taking on its
-- own rather than inside a collapse.
--   channel_id: A remnant of the Mattermost plugin. Nothing writes it.
--   type: O — open, P — private.
--   properties: The board's own automation lives here — xciiiColumns, xciiiFlows,
--     xciiiPrompt and the records of which field is which. JSON on purpose:
--     it travels with the board, into an export and into a template.
--   card_properties: The schema of a card's fields. The product's main denormalisation, and
--     deliberately left alone: the whole webapp filters and groups on it.
CREATE TABLE "{{.prefix}}boards_history" ("id" character varying(36) NOT NULL, "insert_at" timestamptz NOT NULL DEFAULT NOW(), "team_id" character varying(36) NOT NULL, "channel_id" character varying(36) NULL, "created_by" character varying(36) NULL, "modified_by" character varying(36) NULL, "type" character varying(1) NOT NULL, "title" text NOT NULL, "description" text NULL, "icon" character varying(256) NULL, "show_description" boolean NULL, "is_template" boolean NULL, "template_version" integer NULL DEFAULT 0, "properties" text NULL, "card_properties" text NULL, "create_at" bigint NULL, "update_at" bigint NULL, "delete_at" bigint NULL, "minimum_role" character varying(36) NOT NULL DEFAULT '', PRIMARY KEY ("id", "insert_at"));

-- Where a card's branch is published. Was the `deploys` array in
-- config.json, and a route's stage named it by name.
CREATE TABLE "{{.prefix}}deploy_target" ("id" character varying(36) NOT NULL, "name" character varying(100) NOT NULL, "ssh_host" character varying(255) NOT NULL, "ssh_user" character varying(64) NULL, "ssh_port" bigint NULL, "ssh_key" text NULL, "base_app" character varying(100) NULL, "base_domain" character varying(255) NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"));

-- Where a card's branch is published. Was the `deploys` array in
-- config.json, and a route's stage named it by name.
CREATE UNIQUE INDEX "idx_{{.prefix}}deploy_target_name" ON "{{.prefix}}deploy_target" ("name");

-- Every version of every block. See boards_history.
--   id: Nullable, which a primary key makes impossible in practice — but this
--     is what the migrations leave, and reproducing it is the point.
--   parent_id: The tree inside a board: a comment or a text block hangs off a card.
--   schema: A version number for the row's own shape. Backticked by the fork's
--     queries on MySQL, where `schema` is reserved.
--   fields: The card's field values, {property_id: value}.
--   root_id: Always equal to board_id. A remnant.
CREATE TABLE "{{.prefix}}blocks_history" ("id" character varying(36) NULL, "insert_at" timestamptz NOT NULL DEFAULT NOW(), "parent_id" character varying(36) NULL, "schema" bigint NULL, "type" text NULL, "title" text NULL, "fields" text NULL, "create_at" bigint NULL, "update_at" bigint NULL, "delete_at" bigint NULL, "root_id" character varying(36) NULL, "modified_by" character varying(36) NULL, "channel_id" character varying(36) NULL, "created_by" character varying(36) NULL, "board_id" character varying(36) NULL, PRIMARY KEY ("id", "insert_at"));

-- Who is on a board, and what they may do there.
CREATE TABLE "{{.prefix}}board_members" ("board_id" character varying(36) NOT NULL, "user_id" character varying(36) NOT NULL, "roles" character varying(64) NULL, "scheme_admin" boolean NULL, "scheme_editor" boolean NULL, "scheme_commenter" boolean NULL, "scheme_viewer" boolean NULL, PRIMARY KEY ("board_id", "user_id"));

-- Who is on a board, and what they may do there.
CREATE INDEX "idx_{{.prefix}}board_members_user_id" ON "{{.prefix}}board_members" ("user_id");

-- Who joined or left a board, and when.
CREATE TABLE "{{.prefix}}board_members_history" ("board_id" character varying(36) NOT NULL, "user_id" character varying(36) NOT NULL, "action" character varying(10) NULL, "insert_at" timestamptz NOT NULL DEFAULT NOW(), PRIMARY KEY ("board_id", "user_id", "insert_at"));

-- Who joined or left a board, and when.
CREATE INDEX "idx_{{.prefix}}board_members_history_user_id" ON "{{.prefix}}board_members_history" ("user_id");

-- Who joined or left a board, and when.
CREATE INDEX "idx_{{.prefix}}board_members_history_board_id_user_id" ON "{{.prefix}}board_members_history" ("board_id", "user_id");

-- A group of boards in the sidebar.
CREATE TABLE "{{.prefix}}categories" ("id" character varying(36) NOT NULL, "name" character varying(100) NOT NULL, "user_id" character varying(36) NOT NULL, "team_id" character varying(36) NOT NULL, "channel_id" character varying(36) NULL, "create_at" bigint NULL, "update_at" bigint NULL, "delete_at" bigint NULL, "collapsed" boolean NULL DEFAULT false, "type" character varying(64) NULL, "sort_order" bigint NULL, PRIMARY KEY ("id"));

-- A group of boards in the sidebar.
CREATE INDEX "idx_{{.prefix}}categories_user_id_team_id" ON "{{.prefix}}categories" ("user_id", "team_id");

-- Which board sits in which sidebar group. The surrogate id is
-- upstream's; the row is really the pair, which the unique index says.
CREATE TABLE "{{.prefix}}category_boards" ("id" character varying(36) NOT NULL, "user_id" character varying(36) NOT NULL, "category_id" character varying(36) NOT NULL, "board_id" character varying(36) NOT NULL, "create_at" bigint NULL, "update_at" bigint NULL, "sort_order" bigint NULL, "hidden" boolean NULL, PRIMARY KEY ("id"));

-- Which board sits in which sidebar group. The surrogate id is
-- upstream's; the row is really the pair, which the unique index says.
CREATE UNIQUE INDEX "{{.prefix}}unique_user_category_board" ON "{{.prefix}}category_boards" ("user_id", "board_id");

-- A board's public link. The id is the board's, so this is one-to-one.
--   id: Nullable, which the migrations leave and this reproduces.
--   workspace_id: An older remnant than channel_id: workspaces predated teams.
CREATE TABLE "{{.prefix}}sharing" ("id" character varying(36) NULL, "enabled" boolean NULL, "token" character varying(100) NULL, "modified_by" character varying(36) NULL, "update_at" bigint NULL, "workspace_id" character varying(36) NULL, PRIMARY KEY ("id"));

-- An attachment. It has no primary key, which is what the migrations
-- leave: 000041 was where one would have been added, and this is a
-- reproduction rather than a repair.
CREATE TABLE "{{.prefix}}file_info" ("id" character varying(26) NOT NULL, "create_at" bigint NOT NULL, "delete_at" bigint NULL, "name" text NOT NULL, "extension" character varying(50) NOT NULL, "size" bigint NOT NULL, "archived" boolean NULL, "path" character varying(512) NULL);

-- What a person chose, per category and name. Not where this app keeps
-- the page's own settings — those are <dataDir>/ui-settings.json, because
-- the desktop window opens on a fresh origin every launch.
CREATE TABLE "{{.prefix}}preferences" ("userid" character varying(36) NOT NULL, "category" character varying(32) NOT NULL, "name" character varying(32) NOT NULL, "value" text NULL, PRIMARY KEY ("userid", "category", "name"));

-- What a person chose, per category and name. Not where this app keeps
-- the page's own settings — those are <dataDir>/ui-settings.json, because
-- the desktop window opens on a fresh origin every launch.
CREATE INDEX "idx_{{.prefix}}preferences_category" ON "{{.prefix}}preferences" ("category");

-- What a person chose, per category and name. Not where this app keeps
-- the page's own settings — those are <dataDir>/ui-settings.json, because
-- the desktop window opens on a fresh origin every launch.
CREATE INDEX "idx_{{.prefix}}preferences_name" ON "{{.prefix}}preferences" ("name");

-- Who is watching a block, for the notification service.
--   block_id: Nullable, which the migrations leave and this reproduces.
--   subscriber_id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE "{{.prefix}}subscriptions" ("block_type" character varying(10) NULL, "block_id" character varying(36) NULL, "workspace_id" character varying(36) NULL, "subscriber_type" character varying(10) NULL, "subscriber_id" character varying(36) NULL, "notified_at" bigint NULL, "create_at" bigint NULL, "delete_at" bigint NULL, PRIMARY KEY ("block_id", "subscriber_id"));

-- Who is watching a block, for the notification service.
--   block_id: Nullable, which the migrations leave and this reproduces.
--   subscriber_id: Nullable, which the migrations leave and this reproduces.
CREATE INDEX "idx_{{.prefix}}subscriptions_subscriber_id" ON "{{.prefix}}subscriptions" ("subscriber_id");

-- The team a board belongs to. In this product there is exactly one and
-- its id is '0' — but the column is in two hundred queries of the fork,
-- and working with teams stays as it is.
--   id: Nullable, which the migrations leave and this reproduces.
CREATE TABLE "{{.prefix}}teams" ("id" character varying(36) NULL, "signup_token" character varying(100) NOT NULL, "settings" text NULL, "modified_by" character varying(36) NULL, "update_at" bigint NULL, PRIMARY KEY ("id"));

-- Network settings several agents share, so they are edited in one
-- place. Was the `proxies` array in config.json.
--   password: Kept apart from the URL so it is entered raw and masked on screen.
--     Still stored in the clear here, exactly as it was in the settings
--     file: moving it into internal/secrets is its own change.
CREATE TABLE "{{.prefix}}proxy" ("id" character varying(36) NOT NULL, "name" character varying(100) NOT NULL, "url" text NULL, "no_proxy" text NULL, "ca_cert" text NULL, "username" character varying(100) NULL, "password" text NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"));

-- Network settings several agents share, so they are edited in one
-- place. Was the `proxies` array in config.json.
--   password: Kept apart from the URL so it is entered raw and masked on screen.
--     Still stored in the clear here, exactly as it was in the settings
--     file: moving it into internal/secrets is its own change.
CREATE UNIQUE INDEX "idx_{{.prefix}}proxy_name" ON "{{.prefix}}proxy" ("name");

-- A registered agent. Its board account is a row in users, and the two
-- are joined by a key rather than by their names happening to match —
-- which is what made renaming an agent break the crew of every route on
-- every board, silently.
--   name: On screen and in the account's username. No longer a reference.
--   user_id: The board account. NULL until one is made, and NULL again if it is
--     deleted: the registry entry is the machine's and outlives it.
--   settings: env, args, cliArgs, options, autoAllowTools, command,
--     terminalCommand, mcpServers. JSON on purpose: this is how to start
--     a process, it points at nothing and nothing joins to it.
CREATE TABLE "{{.prefix}}agent" ("id" character varying(36) NOT NULL, "name" character varying(100) NOT NULL, "kind" character varying(32) NOT NULL, "user_id" character varying(36) NULL, "proxy_id" character varying(36) NULL, "bin_path" text NULL, "model" character varying(100) NULL, "prompt" text NULL, "settings" text NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "agent_user" FOREIGN KEY ("user_id") REFERENCES "{{.prefix}}users" ("id") ON DELETE SET NULL, CONSTRAINT "agent_proxy" FOREIGN KEY ("proxy_id") REFERENCES "{{.prefix}}proxy" ("id") ON DELETE SET NULL);

-- A registered agent. Its board account is a row in users, and the two
-- are joined by a key rather than by their names happening to match —
-- which is what made renaming an agent break the crew of every route on
-- every board, silently.
--   name: On screen and in the account's username. No longer a reference.
--   user_id: The board account. NULL until one is made, and NULL again if it is
--     deleted: the registry entry is the machine's and outlives it.
--   settings: env, args, cliArgs, options, autoAllowTools, command,
--     terminalCommand, mcpServers. JSON on purpose: this is how to start
--     a process, it points at nothing and nothing joins to it.
CREATE UNIQUE INDEX "idx_{{.prefix}}agent_name" ON "{{.prefix}}agent" ("name");

-- Everything on a board: cards, views, comments, text, attachments. A
-- card is a row here with type='card', and it is what every table this
-- application owns points at.
--   id: Nullable, which a primary key makes impossible in practice — but this
--     is what the migrations leave, and reproducing it is the point.
--   parent_id: The tree inside a board: a comment or a text block hangs off a card.
--   schema: A version number for the row's own shape. Backticked by the fork's
--     queries on MySQL, where `schema` is reserved.
--   fields: The card's field values, {property_id: value}.
--   root_id: Always equal to board_id. A remnant.
CREATE TABLE "{{.prefix}}blocks" ("id" character varying(36) NULL, "insert_at" timestamptz NOT NULL DEFAULT NOW(), "parent_id" character varying(36) NULL, "schema" bigint NULL, "type" text NULL, "title" text NULL, "fields" text NULL, "create_at" bigint NULL, "update_at" bigint NULL, "delete_at" bigint NULL, "root_id" character varying(36) NULL, "modified_by" character varying(36) NULL, "channel_id" character varying(36) NULL, "created_by" character varying(36) NULL, "board_id" character varying(36) NULL, PRIMARY KEY ("id"));

-- Everything on a board: cards, views, comments, text, attachments. A
-- card is a row here with type='card', and it is what every table this
-- application owns points at.
--   id: Nullable, which a primary key makes impossible in practice — but this
--     is what the migrations leave, and reproducing it is the point.
--   parent_id: The tree inside a board: a comment or a text block hangs off a card.
--   schema: A version number for the row's own shape. Backticked by the fork's
--     queries on MySQL, where `schema` is reserved.
--   fields: The card's field values, {property_id: value}.
--   root_id: Always equal to board_id. A remnant.
CREATE INDEX "idx_{{.prefix}}blocks_board_id_parent_id" ON "{{.prefix}}blocks" ("board_id", "parent_id");

-- A board.
--   channel_id: A remnant of the Mattermost plugin. Nothing writes it.
--   type: O — open, P — private.
--   properties: The board's own automation lives here — xciiiColumns, xciiiFlows,
--     xciiiPrompt and the records of which field is which. JSON on purpose:
--     it travels with the board, into an export and into a template.
--   card_properties: The schema of a card's fields. The product's main denormalisation, and
--     deliberately left alone: the whole webapp filters and groups on it.
CREATE TABLE "{{.prefix}}boards" ("id" character varying(36) NOT NULL, "insert_at" timestamptz NOT NULL DEFAULT NOW(), "team_id" character varying(36) NOT NULL, "channel_id" character varying(36) NULL, "created_by" character varying(36) NULL, "modified_by" character varying(36) NULL, "type" character varying(1) NOT NULL, "title" text NOT NULL, "description" text NULL, "icon" character varying(256) NULL, "show_description" boolean NULL, "is_template" boolean NULL, "template_version" integer NULL DEFAULT 0, "properties" text NULL, "card_properties" text NULL, "create_at" bigint NULL, "update_at" bigint NULL, "delete_at" bigint NULL, "minimum_role" character varying(36) NOT NULL DEFAULT '', PRIMARY KEY ("id"));

-- A board.
--   channel_id: A remnant of the Mattermost plugin. Nothing writes it.
--   type: O — open, P — private.
--   properties: The board's own automation lives here — xciiiColumns, xciiiFlows,
--     xciiiPrompt and the records of which field is which. JSON on purpose:
--     it travels with the board, into an export and into a template.
--   card_properties: The schema of a card's fields. The product's main denormalisation, and
--     deliberately left alone: the whole webapp filters and groups on it.
CREATE INDEX "idx_{{.prefix}}boards_team_id_is_template" ON "{{.prefix}}boards" ("team_id", "is_template");

-- A board.
--   channel_id: A remnant of the Mattermost plugin. Nothing writes it.
--   type: O — open, P — private.
--   properties: The board's own automation lives here — xciiiColumns, xciiiFlows,
--     xciiiPrompt and the records of which field is which. JSON on purpose:
--     it travels with the board, into an export and into a template.
--   card_properties: The schema of a card's fields. The product's main denormalisation, and
--     deliberately left alone: the whole webapp filters and groups on it.
CREATE INDEX "idx_{{.prefix}}boards_channel_id" ON "{{.prefix}}boards" ("channel_id");

-- A run of an agent over ACP. One process, one verdict: unlike a
-- conversation, it is never resumed, which is why the two are
-- separate tables and not one row with a transport column.
--   card_id: NULL for a run that is about no card — naming a branch is one.
--   finished_at: NULL means the session is still live.
CREATE TABLE "{{.prefix}}agent_session" ("id" character varying(36) NOT NULL, "card_id" character varying(36) NULL, "board_id" character varying(36) NULL, "agent_kind" character varying(32) NOT NULL, "acp_session_id" character varying(100) NULL, "status" character varying(24) NOT NULL, "cwd" text NULL, "worktree_path" text NULL, "branch" character varying(255) NULL, "started_at" bigint NOT NULL, "finished_at" bigint NULL, "error_text" text NULL, PRIMARY KEY ("id"), CONSTRAINT "agent_session_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE, CONSTRAINT "agent_session_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- A run of an agent over ACP. One process, one verdict: unlike a
-- conversation, it is never resumed, which is why the two are
-- separate tables and not one row with a transport column.
--   card_id: NULL for a run that is about no card — naming a branch is one.
--   finished_at: NULL means the session is still live.
CREATE INDEX "idx_{{.prefix}}agent_session_card" ON "{{.prefix}}agent_session" ("card_id", "started_at");

-- Which setup questions a board has been asked. It is about this machine
-- — the answers are folders and hosts here — so it cannot live in the
-- browser's storage, which the desktop window forgets on every launch.
--   changed_at: Was `at`. AT is a keyword in Postgres and a name not worth having.
CREATE TABLE "{{.prefix}}board_setup" ("board_id" character varying(36) NOT NULL, "step" character varying(32) NOT NULL, "status" character varying(16) NOT NULL, "changed_at" bigint NOT NULL, PRIMARY KEY ("board_id", "step"), CONSTRAINT "board_setup_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- One current reason a card is not moving — not a journal. The reason is
-- true only until somebody fixes what it is about, and a comment would
-- outlive it as noise.
--   kind: 'conversation' is the one kind with somewhere to go: open the
--     terminal. The rest have no button, which is why this is a field and
--     never a reading of the reason's own Russian.
CREATE TABLE "{{.prefix}}card_stall" ("card_id" character varying(36) NOT NULL, "node_id" character varying(64) NULL, "kind" character varying(32) NULL, "reason" text NOT NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("card_id"), CONSTRAINT "card_stall_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE);

-- A named place an agent can work in. Was the `projects` array in
-- config.json; a card points at it by id, which is also the id of the
-- board option offered for it, so a card naming its folder is a card
-- holding an ordinary select value that happens to be a reference.
--   name: A caption, not a key. Renaming it breaks nothing, which is the
--     whole reason the id exists.
--   board_id: The board that offers this folder, and the only one that does.
--     NULL means no board has claimed it — a state the product already
--     has a name and a screen for, which is why a deleted board sets this
--     to NULL rather than taking the registry entry with it.
--   global: «На всех досках»: one entry seen from several boards, which is what
--     makes the mode belong to the pair rather than to the folder.
--   kind: What somebody was promised, not what the folder happens to be:
--     'git' means a repository was demanded and one without git is an
--     error. NULL is the ordinary case and means nobody said.
CREATE TABLE "{{.prefix}}workspace" ("id" character varying(36) NOT NULL, "name" character varying(200) NOT NULL, "path" text NULL, "board_id" character varying(36) NULL, "global" boolean NOT NULL, "kind" character varying(16) NULL, "base_branch" character varying(200) NULL, "branch_prefix" character varying(64) NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "workspace_offered_on" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE SET NULL);

-- A named place an agent can work in. Was the `projects` array in
-- config.json; a card points at it by id, which is also the id of the
-- board option offered for it, so a card naming its folder is a card
-- holding an ordinary select value that happens to be a reference.
--   name: A caption, not a key. Renaming it breaks nothing, which is the
--     whole reason the id exists.
--   board_id: The board that offers this folder, and the only one that does.
--     NULL means no board has claimed it — a state the product already
--     has a name and a screen for, which is why a deleted board sets this
--     to NULL rather than taking the registry entry with it.
--   global: «На всех досках»: one entry seen from several boards, which is what
--     makes the mode belong to the pair rather than to the folder.
--   kind: What somebody was promised, not what the folder happens to be:
--     'git' means a repository was demanded and one without git is an
--     error. NULL is the ordinary case and means nobody said.
CREATE UNIQUE INDEX "idx_{{.prefix}}workspace_name" ON "{{.prefix}}workspace" ("name");

-- The directory and the branch one owner holds in one workspace. The
-- owner is a card, or a board for a conversation with no card — two
-- nullable columns rather than one string, because a foreign key cannot
-- point at two tables through one.
--   id: A surrogate, and the one place in this schema where that is right:
--     the natural key would have to include a nullable column, which MySQL
--     and Postgres forbid in a primary key. Uniqueness is stated in the
--     indexes below instead, where a NULL is allowed to differ from a NULL.
--     Nothing outside this application creates a checkout, so no client has
--     to be able to supply the id.
--   board_id: Set for «черновики доски»: a conversation with no card still works
--     somewhere, and that somewhere belongs to the board.
--   path: Where the copy is. Not the workspace's own path — that is on the
--     workspace, and this is the worktree cut from it.
--   base: What the branch was cut from, and therefore what «merged» means.
--   released_at: NULL means the checkout is live.
CREATE TABLE "{{.prefix}}checkout" ("id" character varying(36) NOT NULL, "workspace_id" character varying(36) NOT NULL, "card_id" character varying(36) NULL, "board_id" character varying(36) NULL, "mode" character varying(16) NOT NULL, "branch" character varying(255) NULL, "path" text NULL, "base" character varying(255) NULL, "created_at" bigint NOT NULL, "released_at" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "checkout_workspace" FOREIGN KEY ("workspace_id") REFERENCES "{{.prefix}}workspace" ("id") ON DELETE RESTRICT, CONSTRAINT "checkout_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE, CONSTRAINT "checkout_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- The directory and the branch one owner holds in one workspace. The
-- owner is a card, or a board for a conversation with no card — two
-- nullable columns rather than one string, because a foreign key cannot
-- point at two tables through one.
--   id: A surrogate, and the one place in this schema where that is right:
--     the natural key would have to include a nullable column, which MySQL
--     and Postgres forbid in a primary key. Uniqueness is stated in the
--     indexes below instead, where a NULL is allowed to differ from a NULL.
--     Nothing outside this application creates a checkout, so no client has
--     to be able to supply the id.
--   board_id: Set for «черновики доски»: a conversation with no card still works
--     somewhere, and that somewhere belongs to the board.
--   path: Where the copy is. Not the workspace's own path — that is on the
--     workspace, and this is the worktree cut from it.
--   base: What the branch was cut from, and therefore what «merged» means.
--   released_at: NULL means the checkout is live.
CREATE UNIQUE INDEX "idx_{{.prefix}}checkout_card" ON "{{.prefix}}checkout" ("workspace_id", "card_id");

-- The directory and the branch one owner holds in one workspace. The
-- owner is a card, or a board for a conversation with no card — two
-- nullable columns rather than one string, because a foreign key cannot
-- point at two tables through one.
--   id: A surrogate, and the one place in this schema where that is right:
--     the natural key would have to include a nullable column, which MySQL
--     and Postgres forbid in a primary key. Uniqueness is stated in the
--     indexes below instead, where a NULL is allowed to differ from a NULL.
--     Nothing outside this application creates a checkout, so no client has
--     to be able to supply the id.
--   board_id: Set for «черновики доски»: a conversation with no card still works
--     somewhere, and that somewhere belongs to the board.
--   path: Where the copy is. Not the workspace's own path — that is on the
--     workspace, and this is the worktree cut from it.
--   base: What the branch was cut from, and therefore what «merged» means.
--   released_at: NULL means the checkout is live.
CREATE UNIQUE INDEX "idx_{{.prefix}}checkout_board" ON "{{.prefix}}checkout" ("workspace_id", "board_id");

-- The directory and the branch one owner holds in one workspace. The
-- owner is a card, or a board for a conversation with no card — two
-- nullable columns rather than one string, because a foreign key cannot
-- point at two tables through one.
--   id: A surrogate, and the one place in this schema where that is right:
--     the natural key would have to include a nullable column, which MySQL
--     and Postgres forbid in a primary key. Uniqueness is stated in the
--     indexes below instead, where a NULL is allowed to differ from a NULL.
--     Nothing outside this application creates a checkout, so no client has
--     to be able to supply the id.
--   board_id: Set for «черновики доски»: a conversation with no card still works
--     somewhere, and that somewhere belongs to the board.
--   path: Where the copy is. Not the workspace's own path — that is on the
--     workspace, and this is the worktree cut from it.
--   base: What the branch was cut from, and therefore what «merged» means.
--   released_at: NULL means the checkout is live.
CREATE INDEX "idx_{{.prefix}}checkout_live" ON "{{.prefix}}checkout" ("workspace_id", "released_at");

-- A conversation with an agent: its CLI in a pty, keyed (card, node).
-- The row outlives every process that ever drew it — that is what makes
-- a conversation resumable, and it is the difference from agent_session,
-- which is one run and then over.
--   card_id: NULL for a planning conversation: it is about no card.
--   node_id: The column's option id — work; '@talk' — discussion; '@none' — a
--     card with no column at all.
--   column_name: What the column was called at the time, frozen: the option may be
--     gone, and the row still has to read the same.
--   summary: The agent's own line about what this conversation is doing.
--   workdir_path: Was repo_path. Becomes workspace_id in the second half of step 2,
--     together with the code that resolves a folder to its registry id.
CREATE TABLE "{{.prefix}}conversation" ("id" character varying(36) NOT NULL, "card_id" character varying(36) NULL, "board_id" character varying(36) NULL, "node_id" character varying(64) NOT NULL, "column_name" character varying(200) NULL, "title" text NULL, "summary" text NULL, "agent" character varying(100) NULL, "kind" character varying(32) NULL, "workdir_path" text NULL, "cwd" text NULL, "branch" character varying(255) NULL, "started_at" bigint NOT NULL, "ended_at" bigint NULL, "exit_code" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "conversation_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE, CONSTRAINT "conversation_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- A conversation with an agent: its CLI in a pty, keyed (card, node).
-- The row outlives every process that ever drew it — that is what makes
-- a conversation resumable, and it is the difference from agent_session,
-- which is one run and then over.
--   card_id: NULL for a planning conversation: it is about no card.
--   node_id: The column's option id — work; '@talk' — discussion; '@none' — a
--     card with no column at all.
--   column_name: What the column was called at the time, frozen: the option may be
--     gone, and the row still has to read the same.
--   summary: The agent's own line about what this conversation is doing.
--   workdir_path: Was repo_path. Becomes workspace_id in the second half of step 2,
--     together with the code that resolves a folder to its registry id.
CREATE INDEX "idx_{{.prefix}}conversation_card" ON "{{.prefix}}conversation" ("card_id", "started_at");

-- A conversation with an agent: its CLI in a pty, keyed (card, node).
-- The row outlives every process that ever drew it — that is what makes
-- a conversation resumable, and it is the difference from agent_session,
-- which is one run and then over.
--   card_id: NULL for a planning conversation: it is about no card.
--   node_id: The column's option id — work; '@talk' — discussion; '@none' — a
--     card with no column at all.
--   column_name: What the column was called at the time, frozen: the option may be
--     gone, and the row still has to read the same.
--   summary: The agent's own line about what this conversation is doing.
--   workdir_path: Was repo_path. Becomes workspace_id in the second half of step 2,
--     together with the code that resolves a folder to its registry id.
CREATE INDEX "idx_{{.prefix}}conversation_card_node" ON "{{.prefix}}conversation" ("card_id", "node_id", "started_at");

-- Every transition a card made, and what the agent said on it.
--   said: The agent's closing words: what a conversation is told instead of
--     its task when the card comes back to it.
CREATE TABLE "{{.prefix}}flow_event" ("id" character varying(36) NOT NULL, "card_id" character varying(36) NOT NULL, "flow" character varying(200) NOT NULL, "from_node" character varying(64) NULL, "to_node" character varying(64) NOT NULL, "on_kind" character varying(32) NOT NULL, "detail" text NULL, "said" text NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "flow_event_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE);

-- Every transition a card made, and what the agent said on it.
--   said: The agent's closing words: what a conversation is told instead of
--     its task when the card comes back to it.
CREATE INDEX "idx_{{.prefix}}flow_event_card" ON "{{.prefix}}flow_event" ("card_id", "id");

-- This machine's index of where each card is on its route. The truth is
-- on the card itself, so it travels with the board; this is what the VCS
-- watcher asks "which cards are parked and on what branch" in one query.
--   flow: The route's name. It has no id of its own yet — contradiction 4 of
--     docs/model-graph.md, which lives inside the board's JSON.
CREATE TABLE "{{.prefix}}flow_state" ("card_id" character varying(36) NOT NULL, "board_id" character varying(36) NULL, "flow" character varying(200) NOT NULL, "node_id" character varying(64) NOT NULL, "branch" character varying(255) NULL, "workdir_path" text NULL, "entered_at" bigint NOT NULL, PRIMARY KEY ("card_id"), CONSTRAINT "flow_state_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE, CONSTRAINT "flow_state_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- What happened during a session, in order. The id is a UUIDv7 rather
-- than an autoincrement: v7 sorts by time, so ORDER BY id still means
-- "as it happened" and the three spellings of AUTO_INCREMENT are gone.
-- `seq` went with them — it was the same fact told twice.
CREATE TABLE "{{.prefix}}session_event" ("id" character varying(36) NOT NULL, "session_id" character varying(36) NOT NULL, "kind" character varying(32) NOT NULL, "payload_json" text NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "session_event_session" FOREIGN KEY ("session_id") REFERENCES "{{.prefix}}agent_session" ("id") ON DELETE CASCADE);

-- What happened during a session, in order. The id is a UUIDv7 rather
-- than an autoincrement: v7 sorts by time, so ORDER BY id still means
-- "as it happened" and the three spellings of AUTO_INCREMENT are gone.
-- `seq` went with them — it was the same fact told twice.
CREATE INDEX "idx_{{.prefix}}session_event_session" ON "{{.prefix}}session_event" ("session_id", "id");

-- Why nothing happened — the only question anybody asks of a source.
-- Deleting the card it produced does not delete the line: what a source
-- decided is a fact about the source.
CREATE TABLE "{{.prefix}}source_event" ("id" character varying(36) NOT NULL, "source" character varying(100) NOT NULL, "external_id" character varying(255) NULL, "rule" character varying(100) NULL, "outcome" character varying(16) NOT NULL, "card_id" character varying(36) NULL, "detail" text NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "source_event_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE SET NULL);

-- Why nothing happened — the only question anybody asks of a source.
-- Deleting the card it produced does not delete the line: what a source
-- decided is a fact about the source.
CREATE INDEX "idx_{{.prefix}}source_event_source" ON "{{.prefix}}source_event" ("source", "id");

-- What a source has already brought. The same letter arriving twice adds
-- to the card it made rather than making a second one.
--   version: The service's own updated/etag: changed means there is something
--     to add.
CREATE TABLE "{{.prefix}}source_item" ("source" character varying(100) NOT NULL, "external_id" character varying(255) NOT NULL, "version" character varying(255) NULL, "card_id" character varying(36) NULL, "created_at" bigint NOT NULL, "updated_at" bigint NOT NULL, PRIMARY KEY ("source", "external_id"), CONSTRAINT "source_item_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE SET NULL);

-- What a source has already brought. The same letter arriving twice adds
-- to the card it made rather than making a second one.
--   version: The service's own updated/etag: changed means there is something
--     to add.
CREATE INDEX "idx_{{.prefix}}source_item_card" ON "{{.prefix}}source_item" ("card_id");

-- A card waiting for its column to free up a place.
--   column_key: board|option — the queue belongs to one column of one board.
CREATE TABLE "{{.prefix}}stage_queue" ("card_id" character varying(36) NOT NULL, "board_id" character varying(36) NULL, "column_key" character varying(128) NOT NULL, "flow" character varying(200) NULL, "node_id" character varying(64) NULL, "queued_at" bigint NOT NULL, PRIMARY KEY ("card_id"), CONSTRAINT "stage_queue_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE, CONSTRAINT "stage_queue_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- A card waiting for its column to free up a place.
--   column_key: board|option — the queue belongs to one column of one board.
CREATE INDEX "idx_{{.prefix}}stage_queue_column" ON "{{.prefix}}stage_queue" ("column_key", "queued_at");

-- This branch event has already been acted on. Keyed by the workspace
-- rather than by its path: a folder somebody moved used to keep its
-- latches, and MySQL would refuse a path in a key of any real length.
--   marker: The commit the event refers to: the same state seen twice fires once.
CREATE TABLE "{{.prefix}}vcs_seen" ("workspace_id" character varying(36) NOT NULL, "branch" character varying(255) NOT NULL, "kind" character varying(32) NOT NULL, "marker" character varying(64) NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("workspace_id", "branch", "kind"), CONSTRAINT "vcs_seen_workspace" FOREIGN KEY ("workspace_id") REFERENCES "{{.prefix}}workspace" ("id") ON DELETE CASCADE);

-- Which board a folder is offered to and how work happens in it there.
-- Keyed by the pair rather than by the folder, because a folder marked
-- «на всех досках» is one entry with a different answer per board: a copy
-- per card where three people work it, a branch in place where one does.
-- Was WorkdirEntry.Modes, a map keyed by board id.
--   mode: worktree | branch. NULL means nobody answered, and the machine's
--     own default stands in.
CREATE TABLE "{{.prefix}}workspace_board" ("workspace_id" character varying(36) NOT NULL, "board_id" character varying(36) NOT NULL, "mode" character varying(16) NULL, PRIMARY KEY ("workspace_id", "board_id"), CONSTRAINT "workspace_board_workspace" FOREIGN KEY ("workspace_id") REFERENCES "{{.prefix}}workspace" ("id") ON DELETE CASCADE, CONSTRAINT "workspace_board_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);
{{end}}
