-- Generated by tools/schemagen. Do not edit by hand: change the schema there
-- and run `go generate ./tools/schemagen`.
--
-- The three dialects below say the same thing. Writing them by hand is what
-- eighty migrations of this fork do, and every one of them is a place where
-- somebody has to remember three answers to one question.

{{if .sqlite}}
-- Network settings several agents share, so they are edited in one
-- place. Was the `proxies` array in config.json.
--   password: Kept apart from the URL so it is entered raw and masked on screen.
--     Still stored in the clear here, exactly as it was in the settings
--     file: moving it into internal/secrets is its own change.
CREATE TABLE `{{.prefix}}proxy` (`id` varchar NOT NULL, `name` varchar NOT NULL, `url` text NULL, `no_proxy` text NULL, `ca_cert` text NULL, `username` varchar NULL, `password` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `idx_{{.prefix}}proxy_name` ON `{{.prefix}}proxy` (`name`);

-- A named place an agent can work in. Was the `projects` array in
-- config.json; a card points at it by id, which is also the id of the
-- board option offered for it, so a card naming its folder is a card
-- holding an ordinary select value that happens to be a reference.
--   name: A caption, not a key. Renaming it breaks nothing, which is the
--     whole reason the id exists.
--   board_id: The board that offers this folder, and the only one that does.
--     NULL means no board has claimed it — a state the product already
--     has a name and a screen for, which is why a deleted board sets this
--     to NULL rather than taking the registry entry with it.
--   global: «На всех досках»: one entry seen from several boards, which is what
--     makes the mode belong to the pair rather than to the folder.
--   kind: What somebody was promised, not what the folder happens to be:
--     'git' means a repository was demanded and one without git is an
--     error. NULL is the ordinary case and means nobody said.
CREATE TABLE `{{.prefix}}workspace` (`id` varchar NOT NULL, `name` varchar NOT NULL, `path` text NULL, `board_id` varchar NULL, `global` boolean NOT NULL, `kind` varchar NULL, `base_branch` varchar NULL, `branch_prefix` varchar NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `workspace_offered_on` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE SET NULL);

CREATE UNIQUE INDEX `idx_{{.prefix}}workspace_name` ON `{{.prefix}}workspace` (`name`);

-- Which board a folder is offered to and how work happens in it there.
-- Keyed by the pair rather than by the folder, because a folder marked
-- «на всех досках» is one entry with a different answer per board: a copy
-- per card where three people work it, a branch in place where one does.
-- Was WorkdirEntry.Modes, a map keyed by board id.
--   mode: worktree | branch. NULL means nobody answered, and the machine's
--     own default stands in.
CREATE TABLE `{{.prefix}}workspace_board` (`workspace_id` varchar NOT NULL, `board_id` varchar NOT NULL, `mode` varchar NULL, PRIMARY KEY (`workspace_id`, `board_id`), CONSTRAINT `workspace_board_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `{{.prefix}}workspace` (`id`) ON DELETE CASCADE, CONSTRAINT `workspace_board_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

-- A registered agent. Its board account is a row in users, and the two
-- are joined by a key rather than by their names happening to match —
-- which is what made renaming an agent break the crew of every route on
-- every board, silently.
--   name: On screen and in the account's username. No longer a reference.
--   user_id: The board account. NULL until one is made, and NULL again if it is
--     deleted: the registry entry is the machine's and outlives it.
--   settings: env, args, cliArgs, options, autoAllowTools, command,
--     terminalCommand, mcpServers. JSON on purpose: this is how to start
--     a process, it points at nothing and nothing joins to it.
CREATE TABLE `{{.prefix}}agent` (`id` varchar NOT NULL, `name` varchar NOT NULL, `kind` varchar NOT NULL, `user_id` varchar NULL, `proxy_id` varchar NULL, `bin_path` text NULL, `model` varchar NULL, `prompt` text NULL, `settings` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `agent_user` FOREIGN KEY (`user_id`) REFERENCES `{{.prefix}}users` (`id`) ON DELETE SET NULL, CONSTRAINT `agent_proxy` FOREIGN KEY (`proxy_id`) REFERENCES `{{.prefix}}proxy` (`id`) ON DELETE SET NULL);

CREATE UNIQUE INDEX `idx_{{.prefix}}agent_name` ON `{{.prefix}}agent` (`name`);

-- Where a card's branch is published. Was the `deploys` array in
-- config.json, and a route's stage named it by name.
CREATE TABLE `{{.prefix}}deploy_target` (`id` varchar NOT NULL, `name` varchar NOT NULL, `ssh_host` varchar NOT NULL, `ssh_user` varchar NULL, `ssh_port` bigint NULL, `ssh_key` text NULL, `base_app` varchar NULL, `base_domain` varchar NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `idx_{{.prefix}}deploy_target_name` ON `{{.prefix}}deploy_target` (`name`);

-- A run of an agent over ACP. One process, one verdict: unlike a
-- conversation, it is never resumed, which is why the two are
-- separate tables and not one row with a transport column.
--   card_id: NULL for a run that is about no card — naming a branch is one.
--   finished_at: NULL means the session is still live.
CREATE TABLE `{{.prefix}}agent_session` (`id` varchar NOT NULL, `card_id` varchar NULL, `board_id` varchar NULL, `agent_kind` varchar NOT NULL, `acp_session_id` varchar NULL, `status` varchar NOT NULL, `cwd` text NULL, `worktree_path` text NULL, `branch` varchar NULL, `started_at` bigint NOT NULL, `finished_at` bigint NULL, `error_text` text NULL, PRIMARY KEY (`id`), CONSTRAINT `agent_session_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `agent_session_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

CREATE INDEX `idx_{{.prefix}}agent_session_card` ON `{{.prefix}}agent_session` (`card_id`, `started_at`);

-- What happened during a session, in order. The id is a UUIDv7 rather
-- than an autoincrement: v7 sorts by time, so ORDER BY id still means
-- "as it happened" and the three spellings of AUTO_INCREMENT are gone.
-- `seq` went with them — it was the same fact told twice.
CREATE TABLE `{{.prefix}}session_event` (`id` varchar NOT NULL, `session_id` varchar NOT NULL, `kind` varchar NOT NULL, `payload_json` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `session_event_session` FOREIGN KEY (`session_id`) REFERENCES `{{.prefix}}agent_session` (`id`) ON DELETE CASCADE);

CREATE INDEX `idx_{{.prefix}}session_event_session` ON `{{.prefix}}session_event` (`session_id`, `id`);

-- A conversation with an agent: its CLI in a pty, keyed (card, node).
-- The row outlives every process that ever drew it — that is what makes
-- a conversation resumable, and it is the difference from agent_session,
-- which is one run and then over.
--   card_id: NULL for a planning conversation: it is about no card.
--   node_id: The column's option id — work; '@talk' — discussion; '@none' — a
--     card with no column at all.
--   column_name: What the column was called at the time, frozen: the option may be
--     gone, and the row still has to read the same.
--   summary: The agent's own line about what this conversation is doing.
--   workdir_path: Was repo_path. Becomes workspace_id in the second half of step 2,
--     together with the code that resolves a folder to its registry id.
CREATE TABLE `{{.prefix}}conversation` (`id` varchar NOT NULL, `card_id` varchar NULL, `board_id` varchar NULL, `node_id` varchar NOT NULL, `column_name` varchar NULL, `title` text NULL, `summary` text NULL, `agent` varchar NULL, `kind` varchar NULL, `workdir_path` text NULL, `cwd` text NULL, `branch` varchar NULL, `started_at` bigint NOT NULL, `ended_at` bigint NULL, `exit_code` bigint NULL, PRIMARY KEY (`id`), CONSTRAINT `conversation_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `conversation_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

CREATE INDEX `idx_{{.prefix}}conversation_card` ON `{{.prefix}}conversation` (`card_id`, `started_at`);

CREATE INDEX `idx_{{.prefix}}conversation_card_node` ON `{{.prefix}}conversation` (`card_id`, `node_id`, `started_at`);

-- One route event, handled once. `key` was the column's name and is a
-- reserved word in MySQL, so it is `token` — cheaper than backticks in
-- every query for ever.
CREATE TABLE `{{.prefix}}idempotency` (`token` varchar NOT NULL, `session_id` varchar NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`token`));

CREATE INDEX `idx_{{.prefix}}idempotency_created` ON `{{.prefix}}idempotency` (`created_at`);

-- This machine's index of where each card is on its route. The truth is
-- on the card itself, so it travels with the board; this is what the VCS
-- watcher asks "which cards are parked and on what branch" in one query.
--   flow: The route's name. It has no id of its own yet — contradiction 4 of
--     docs/model-graph.md, which lives inside the board's JSON.
CREATE TABLE `{{.prefix}}flow_state` (`card_id` varchar NOT NULL, `board_id` varchar NULL, `flow` varchar NOT NULL, `node_id` varchar NOT NULL, `branch` varchar NULL, `workdir_path` text NULL, `entered_at` bigint NOT NULL, PRIMARY KEY (`card_id`), CONSTRAINT `flow_state_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `flow_state_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

-- Every transition a card made, and what the agent said on it.
--   said: The agent's closing words: what a conversation is told instead of
--     its task when the card comes back to it.
CREATE TABLE `{{.prefix}}flow_event` (`id` varchar NOT NULL, `card_id` varchar NOT NULL, `flow` varchar NOT NULL, `from_node` varchar NULL, `to_node` varchar NOT NULL, `on_kind` varchar NOT NULL, `detail` text NULL, `said` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `flow_event_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE);

CREATE INDEX `idx_{{.prefix}}flow_event_card` ON `{{.prefix}}flow_event` (`card_id`, `id`);

-- One current reason a card is not moving — not a journal. The reason is
-- true only until somebody fixes what it is about, and a comment would
-- outlive it as noise.
--   kind: 'conversation' is the one kind with somewhere to go: open the
--     terminal. The rest have no button, which is why this is a field and
--     never a reading of the reason's own Russian.
CREATE TABLE `{{.prefix}}card_stall` (`card_id` varchar NOT NULL, `node_id` varchar NULL, `kind` varchar NULL, `reason` text NOT NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`card_id`), CONSTRAINT `card_stall_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE);

-- A card waiting for its column to free up a place.
--   column_key: board|option — the queue belongs to one column of one board.
CREATE TABLE `{{.prefix}}stage_queue` (`card_id` varchar NOT NULL, `board_id` varchar NULL, `column_key` varchar NOT NULL, `flow` varchar NULL, `node_id` varchar NULL, `queued_at` bigint NOT NULL, PRIMARY KEY (`card_id`), CONSTRAINT `stage_queue_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `stage_queue_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

CREATE INDEX `idx_{{.prefix}}stage_queue_column` ON `{{.prefix}}stage_queue` (`column_key`, `queued_at`);

-- Which setup questions a board has been asked. It is about this machine
-- — the answers are folders and hosts here — so it cannot live in the
-- browser's storage, which the desktop window forgets on every launch.
--   changed_at: Was `at`. AT is a keyword in Postgres and a name not worth having.
CREATE TABLE `{{.prefix}}board_setup` (`board_id` varchar NOT NULL, `step` varchar NOT NULL, `status` varchar NOT NULL, `changed_at` bigint NOT NULL, PRIMARY KEY (`board_id`, `step`), CONSTRAINT `board_setup_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE);

-- This branch event has already been acted on. Keyed by path still; the
-- second half of step 2 moves it onto the workspace id, which is also what
-- stops MySQL refusing a path in a key of any real length.
--   marker: The commit the event refers to: the same state seen twice fires once.
CREATE TABLE `{{.prefix}}vcs_seen` (`workdir_path` varchar NOT NULL, `branch` varchar NOT NULL, `kind` varchar NOT NULL, `marker` varchar NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`workdir_path`, `branch`, `kind`));

-- The copy and the branch one owner holds in one folder. No foreign key
-- here yet, for the reason above.
--   branch: NULL for an ordinary folder: it has no branch, and that is absence
--     rather than an empty name.
--   released_at: NULL means the workspace is live.
CREATE TABLE `{{.prefix}}workdir_claim` (`workdir_path` varchar NOT NULL, `owner` varchar NOT NULL, `mode` varchar NOT NULL, `branch` varchar NULL, `path` text NULL, `base` varchar NULL, `created_at` bigint NOT NULL, `released_at` bigint NULL, PRIMARY KEY (`workdir_path`, `owner`));

CREATE INDEX `idx_{{.prefix}}workdir_claim_live` ON `{{.prefix}}workdir_claim` (`workdir_path`, `released_at`);

-- What a source has already brought. The same letter arriving twice adds
-- to the card it made rather than making a second one.
--   version: The service's own updated/etag: changed means there is something
--     to add.
CREATE TABLE `{{.prefix}}source_item` (`source` varchar NOT NULL, `external_id` varchar NOT NULL, `version` varchar NULL, `card_id` varchar NULL, `created_at` bigint NOT NULL, `updated_at` bigint NOT NULL, PRIMARY KEY (`source`, `external_id`), CONSTRAINT `source_item_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE SET NULL);

CREATE INDEX `idx_{{.prefix}}source_item_card` ON `{{.prefix}}source_item` (`card_id`);

-- Why nothing happened — the only question anybody asks of a source.
-- Deleting the card it produced does not delete the line: what a source
-- decided is a fact about the source.
CREATE TABLE `{{.prefix}}source_event` (`id` varchar NOT NULL, `source` varchar NOT NULL, `external_id` varchar NULL, `rule` varchar NULL, `outcome` varchar NOT NULL, `card_id` varchar NULL, `detail` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `source_event_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE SET NULL);

CREATE INDEX `idx_{{.prefix}}source_event_source` ON `{{.prefix}}source_event` (`source`, `id`);
{{end}}

{{if .mysql}}
-- One route event, handled once. `key` was the column's name and is a
-- reserved word in MySQL, so it is `token` — cheaper than backticks in
-- every query for ever.
CREATE TABLE `{{.prefix}}idempotency` (`token` varchar(255) NOT NULL, `session_id` varchar(36) NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`token`), INDEX `idx_{{.prefix}}idempotency_created` (`created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- The copy and the branch one owner holds in one folder. No foreign key
-- here yet, for the reason above.
--   branch: NULL for an ordinary folder: it has no branch, and that is absence
--     rather than an empty name.
--   released_at: NULL means the workspace is live.
CREATE TABLE `{{.prefix}}workdir_claim` (`workdir_path` varchar(255) NOT NULL, `owner` varchar(128) NOT NULL, `mode` varchar(16) NOT NULL, `branch` varchar(255) NULL, `path` text NULL, `base` varchar(255) NULL, `created_at` bigint NOT NULL, `released_at` bigint NULL, PRIMARY KEY (`workdir_path`, `owner`), INDEX `idx_{{.prefix}}workdir_claim_live` (`workdir_path`, `released_at`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Where a card's branch is published. Was the `deploys` array in
-- config.json, and a route's stage named it by name.
CREATE TABLE `{{.prefix}}deploy_target` (`id` varchar(36) NOT NULL, `name` varchar(100) NOT NULL, `ssh_host` varchar(255) NOT NULL, `ssh_user` varchar(64) NULL, `ssh_port` bigint NULL, `ssh_key` text NULL, `base_app` varchar(100) NULL, `base_domain` varchar(255) NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idx_{{.prefix}}deploy_target_name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- This branch event has already been acted on. Keyed by path still; the
-- second half of step 2 moves it onto the workspace id, which is also what
-- stops MySQL refusing a path in a key of any real length.
--   marker: The commit the event refers to: the same state seen twice fires once.
CREATE TABLE `{{.prefix}}vcs_seen` (`workdir_path` varchar(255) NOT NULL, `branch` varchar(255) NOT NULL, `kind` varchar(32) NOT NULL, `marker` varchar(64) NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`workdir_path`, `branch`, `kind`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Network settings several agents share, so they are edited in one
-- place. Was the `proxies` array in config.json.
--   password: Kept apart from the URL so it is entered raw and masked on screen.
--     Still stored in the clear here, exactly as it was in the settings
--     file: moving it into internal/secrets is its own change.
CREATE TABLE `{{.prefix}}proxy` (`id` varchar(36) NOT NULL, `name` varchar(100) NOT NULL, `url` text NULL, `no_proxy` text NULL, `ca_cert` text NULL, `username` varchar(100) NULL, `password` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idx_{{.prefix}}proxy_name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A registered agent. Its board account is a row in users, and the two
-- are joined by a key rather than by their names happening to match —
-- which is what made renaming an agent break the crew of every route on
-- every board, silently.
--   name: On screen and in the account's username. No longer a reference.
--   user_id: The board account. NULL until one is made, and NULL again if it is
--     deleted: the registry entry is the machine's and outlives it.
--   settings: env, args, cliArgs, options, autoAllowTools, command,
--     terminalCommand, mcpServers. JSON on purpose: this is how to start
--     a process, it points at nothing and nothing joins to it.
CREATE TABLE `{{.prefix}}agent` (`id` varchar(36) NOT NULL, `name` varchar(100) NOT NULL, `kind` varchar(32) NOT NULL, `user_id` varchar(36) NULL, `proxy_id` varchar(36) NULL, `bin_path` text NULL, `model` varchar(100) NULL, `prompt` text NULL, `settings` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idx_{{.prefix}}agent_name` (`name`), CONSTRAINT `agent_user` FOREIGN KEY (`user_id`) REFERENCES `{{.prefix}}users` (`id`) ON DELETE SET NULL, CONSTRAINT `agent_proxy` FOREIGN KEY (`proxy_id`) REFERENCES `{{.prefix}}proxy` (`id`) ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A run of an agent over ACP. One process, one verdict: unlike a
-- conversation, it is never resumed, which is why the two are
-- separate tables and not one row with a transport column.
--   card_id: NULL for a run that is about no card — naming a branch is one.
--   finished_at: NULL means the session is still live.
CREATE TABLE `{{.prefix}}agent_session` (`id` varchar(36) NOT NULL, `card_id` varchar(36) NULL, `board_id` varchar(36) NULL, `agent_kind` varchar(32) NOT NULL, `acp_session_id` varchar(100) NULL, `status` varchar(24) NOT NULL, `cwd` text NULL, `worktree_path` text NULL, `branch` varchar(255) NULL, `started_at` bigint NOT NULL, `finished_at` bigint NULL, `error_text` text NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}agent_session_card` (`card_id`, `started_at`), CONSTRAINT `agent_session_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `agent_session_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Which setup questions a board has been asked. It is about this machine
-- — the answers are folders and hosts here — so it cannot live in the
-- browser's storage, which the desktop window forgets on every launch.
--   changed_at: Was `at`. AT is a keyword in Postgres and a name not worth having.
CREATE TABLE `{{.prefix}}board_setup` (`board_id` varchar(36) NOT NULL, `step` varchar(32) NOT NULL, `status` varchar(16) NOT NULL, `changed_at` bigint NOT NULL, PRIMARY KEY (`board_id`, `step`), CONSTRAINT `board_setup_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- One current reason a card is not moving — not a journal. The reason is
-- true only until somebody fixes what it is about, and a comment would
-- outlive it as noise.
--   kind: 'conversation' is the one kind with somewhere to go: open the
--     terminal. The rest have no button, which is why this is a field and
--     never a reading of the reason's own Russian.
CREATE TABLE `{{.prefix}}card_stall` (`card_id` varchar(36) NOT NULL, `node_id` varchar(64) NULL, `kind` varchar(32) NULL, `reason` text NOT NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`card_id`), CONSTRAINT `card_stall_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A conversation with an agent: its CLI in a pty, keyed (card, node).
-- The row outlives every process that ever drew it — that is what makes
-- a conversation resumable, and it is the difference from agent_session,
-- which is one run and then over.
--   card_id: NULL for a planning conversation: it is about no card.
--   node_id: The column's option id — work; '@talk' — discussion; '@none' — a
--     card with no column at all.
--   column_name: What the column was called at the time, frozen: the option may be
--     gone, and the row still has to read the same.
--   summary: The agent's own line about what this conversation is doing.
--   workdir_path: Was repo_path. Becomes workspace_id in the second half of step 2,
--     together with the code that resolves a folder to its registry id.
CREATE TABLE `{{.prefix}}conversation` (`id` varchar(36) NOT NULL, `card_id` varchar(36) NULL, `board_id` varchar(36) NULL, `node_id` varchar(64) NOT NULL, `column_name` varchar(200) NULL, `title` text NULL, `summary` text NULL, `agent` varchar(100) NULL, `kind` varchar(32) NULL, `workdir_path` text NULL, `cwd` text NULL, `branch` varchar(255) NULL, `started_at` bigint NOT NULL, `ended_at` bigint NULL, `exit_code` bigint NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}conversation_card` (`card_id`, `started_at`), INDEX `idx_{{.prefix}}conversation_card_node` (`card_id`, `node_id`, `started_at`), CONSTRAINT `conversation_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `conversation_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Every transition a card made, and what the agent said on it.
--   said: The agent's closing words: what a conversation is told instead of
--     its task when the card comes back to it.
CREATE TABLE `{{.prefix}}flow_event` (`id` varchar(36) NOT NULL, `card_id` varchar(36) NOT NULL, `flow` varchar(200) NOT NULL, `from_node` varchar(64) NULL, `to_node` varchar(64) NOT NULL, `on_kind` varchar(32) NOT NULL, `detail` text NULL, `said` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}flow_event_card` (`card_id`, `id`), CONSTRAINT `flow_event_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- This machine's index of where each card is on its route. The truth is
-- on the card itself, so it travels with the board; this is what the VCS
-- watcher asks "which cards are parked and on what branch" in one query.
--   flow: The route's name. It has no id of its own yet — contradiction 4 of
--     docs/model-graph.md, which lives inside the board's JSON.
CREATE TABLE `{{.prefix}}flow_state` (`card_id` varchar(36) NOT NULL, `board_id` varchar(36) NULL, `flow` varchar(200) NOT NULL, `node_id` varchar(64) NOT NULL, `branch` varchar(255) NULL, `workdir_path` text NULL, `entered_at` bigint NOT NULL, PRIMARY KEY (`card_id`), CONSTRAINT `flow_state_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `flow_state_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- What happened during a session, in order. The id is a UUIDv7 rather
-- than an autoincrement: v7 sorts by time, so ORDER BY id still means
-- "as it happened" and the three spellings of AUTO_INCREMENT are gone.
-- `seq` went with them — it was the same fact told twice.
CREATE TABLE `{{.prefix}}session_event` (`id` varchar(36) NOT NULL, `session_id` varchar(36) NOT NULL, `kind` varchar(32) NOT NULL, `payload_json` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}session_event_session` (`session_id`, `id`), CONSTRAINT `session_event_session` FOREIGN KEY (`session_id`) REFERENCES `{{.prefix}}agent_session` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Why nothing happened — the only question anybody asks of a source.
-- Deleting the card it produced does not delete the line: what a source
-- decided is a fact about the source.
CREATE TABLE `{{.prefix}}source_event` (`id` varchar(36) NOT NULL, `source` varchar(100) NOT NULL, `external_id` varchar(255) NULL, `rule` varchar(100) NULL, `outcome` varchar(16) NOT NULL, `card_id` varchar(36) NULL, `detail` text NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `idx_{{.prefix}}source_event_source` (`source`, `id`), CONSTRAINT `source_event_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- What a source has already brought. The same letter arriving twice adds
-- to the card it made rather than making a second one.
--   version: The service's own updated/etag: changed means there is something
--     to add.
CREATE TABLE `{{.prefix}}source_item` (`source` varchar(100) NOT NULL, `external_id` varchar(255) NOT NULL, `version` varchar(255) NULL, `card_id` varchar(36) NULL, `created_at` bigint NOT NULL, `updated_at` bigint NOT NULL, PRIMARY KEY (`source`, `external_id`), INDEX `idx_{{.prefix}}source_item_card` (`card_id`), CONSTRAINT `source_item_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A card waiting for its column to free up a place.
--   column_key: board|option — the queue belongs to one column of one board.
CREATE TABLE `{{.prefix}}stage_queue` (`card_id` varchar(36) NOT NULL, `board_id` varchar(36) NULL, `column_key` varchar(128) NOT NULL, `flow` varchar(200) NULL, `node_id` varchar(64) NULL, `queued_at` bigint NOT NULL, PRIMARY KEY (`card_id`), INDEX `idx_{{.prefix}}stage_queue_column` (`column_key`, `queued_at`), CONSTRAINT `stage_queue_card` FOREIGN KEY (`card_id`) REFERENCES `{{.prefix}}blocks` (`id`) ON DELETE CASCADE, CONSTRAINT `stage_queue_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- A named place an agent can work in. Was the `projects` array in
-- config.json; a card points at it by id, which is also the id of the
-- board option offered for it, so a card naming its folder is a card
-- holding an ordinary select value that happens to be a reference.
--   name: A caption, not a key. Renaming it breaks nothing, which is the
--     whole reason the id exists.
--   board_id: The board that offers this folder, and the only one that does.
--     NULL means no board has claimed it — a state the product already
--     has a name and a screen for, which is why a deleted board sets this
--     to NULL rather than taking the registry entry with it.
--   global: «На всех досках»: one entry seen from several boards, which is what
--     makes the mode belong to the pair rather than to the folder.
--   kind: What somebody was promised, not what the folder happens to be:
--     'git' means a repository was demanded and one without git is an
--     error. NULL is the ordinary case and means nobody said.
CREATE TABLE `{{.prefix}}workspace` (`id` varchar(36) NOT NULL, `name` varchar(200) NOT NULL, `path` text NULL, `board_id` varchar(36) NULL, `global` bool NOT NULL, `kind` varchar(16) NULL, `base_branch` varchar(200) NULL, `branch_prefix` varchar(64) NULL, `created_at` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idx_{{.prefix}}workspace_name` (`name`), CONSTRAINT `workspace_offered_on` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

-- Which board a folder is offered to and how work happens in it there.
-- Keyed by the pair rather than by the folder, because a folder marked
-- «на всех досках» is one entry with a different answer per board: a copy
-- per card where three people work it, a branch in place where one does.
-- Was WorkdirEntry.Modes, a map keyed by board id.
--   mode: worktree | branch. NULL means nobody answered, and the machine's
--     own default stands in.
CREATE TABLE `{{.prefix}}workspace_board` (`workspace_id` varchar(36) NOT NULL, `board_id` varchar(36) NOT NULL, `mode` varchar(16) NULL, PRIMARY KEY (`workspace_id`, `board_id`), CONSTRAINT `workspace_board_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `{{.prefix}}workspace` (`id`) ON DELETE CASCADE, CONSTRAINT `workspace_board_board` FOREIGN KEY (`board_id`) REFERENCES `{{.prefix}}boards` (`id`) ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
{{end}}

{{if .postgres}}
-- One route event, handled once. `key` was the column's name and is a
-- reserved word in MySQL, so it is `token` — cheaper than backticks in
-- every query for ever.
CREATE TABLE "{{.prefix}}idempotency" ("token" character varying(255) NOT NULL, "session_id" character varying(36) NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("token"));

-- One route event, handled once. `key` was the column's name and is a
-- reserved word in MySQL, so it is `token` — cheaper than backticks in
-- every query for ever.
CREATE INDEX "idx_{{.prefix}}idempotency_created" ON "{{.prefix}}idempotency" ("created_at");

-- The copy and the branch one owner holds in one folder. No foreign key
-- here yet, for the reason above.
--   branch: NULL for an ordinary folder: it has no branch, and that is absence
--     rather than an empty name.
--   released_at: NULL means the workspace is live.
CREATE TABLE "{{.prefix}}workdir_claim" ("workdir_path" character varying(255) NOT NULL, "owner" character varying(128) NOT NULL, "mode" character varying(16) NOT NULL, "branch" character varying(255) NULL, "path" text NULL, "base" character varying(255) NULL, "created_at" bigint NOT NULL, "released_at" bigint NULL, PRIMARY KEY ("workdir_path", "owner"));

-- The copy and the branch one owner holds in one folder. No foreign key
-- here yet, for the reason above.
--   branch: NULL for an ordinary folder: it has no branch, and that is absence
--     rather than an empty name.
--   released_at: NULL means the workspace is live.
CREATE INDEX "idx_{{.prefix}}workdir_claim_live" ON "{{.prefix}}workdir_claim" ("workdir_path", "released_at");

-- Where a card's branch is published. Was the `deploys` array in
-- config.json, and a route's stage named it by name.
CREATE TABLE "{{.prefix}}deploy_target" ("id" character varying(36) NOT NULL, "name" character varying(100) NOT NULL, "ssh_host" character varying(255) NOT NULL, "ssh_user" character varying(64) NULL, "ssh_port" bigint NULL, "ssh_key" text NULL, "base_app" character varying(100) NULL, "base_domain" character varying(255) NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"));

-- Where a card's branch is published. Was the `deploys` array in
-- config.json, and a route's stage named it by name.
CREATE UNIQUE INDEX "idx_{{.prefix}}deploy_target_name" ON "{{.prefix}}deploy_target" ("name");

-- This branch event has already been acted on. Keyed by path still; the
-- second half of step 2 moves it onto the workspace id, which is also what
-- stops MySQL refusing a path in a key of any real length.
--   marker: The commit the event refers to: the same state seen twice fires once.
CREATE TABLE "{{.prefix}}vcs_seen" ("workdir_path" character varying(255) NOT NULL, "branch" character varying(255) NOT NULL, "kind" character varying(32) NOT NULL, "marker" character varying(64) NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("workdir_path", "branch", "kind"));

-- Network settings several agents share, so they are edited in one
-- place. Was the `proxies` array in config.json.
--   password: Kept apart from the URL so it is entered raw and masked on screen.
--     Still stored in the clear here, exactly as it was in the settings
--     file: moving it into internal/secrets is its own change.
CREATE TABLE "{{.prefix}}proxy" ("id" character varying(36) NOT NULL, "name" character varying(100) NOT NULL, "url" text NULL, "no_proxy" text NULL, "ca_cert" text NULL, "username" character varying(100) NULL, "password" text NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"));

-- Network settings several agents share, so they are edited in one
-- place. Was the `proxies` array in config.json.
--   password: Kept apart from the URL so it is entered raw and masked on screen.
--     Still stored in the clear here, exactly as it was in the settings
--     file: moving it into internal/secrets is its own change.
CREATE UNIQUE INDEX "idx_{{.prefix}}proxy_name" ON "{{.prefix}}proxy" ("name");

-- A registered agent. Its board account is a row in users, and the two
-- are joined by a key rather than by their names happening to match —
-- which is what made renaming an agent break the crew of every route on
-- every board, silently.
--   name: On screen and in the account's username. No longer a reference.
--   user_id: The board account. NULL until one is made, and NULL again if it is
--     deleted: the registry entry is the machine's and outlives it.
--   settings: env, args, cliArgs, options, autoAllowTools, command,
--     terminalCommand, mcpServers. JSON on purpose: this is how to start
--     a process, it points at nothing and nothing joins to it.
CREATE TABLE "{{.prefix}}agent" ("id" character varying(36) NOT NULL, "name" character varying(100) NOT NULL, "kind" character varying(32) NOT NULL, "user_id" character varying(36) NULL, "proxy_id" character varying(36) NULL, "bin_path" text NULL, "model" character varying(100) NULL, "prompt" text NULL, "settings" text NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "agent_user" FOREIGN KEY ("user_id") REFERENCES "{{.prefix}}users" ("id") ON DELETE SET NULL, CONSTRAINT "agent_proxy" FOREIGN KEY ("proxy_id") REFERENCES "{{.prefix}}proxy" ("id") ON DELETE SET NULL);

-- A registered agent. Its board account is a row in users, and the two
-- are joined by a key rather than by their names happening to match —
-- which is what made renaming an agent break the crew of every route on
-- every board, silently.
--   name: On screen and in the account's username. No longer a reference.
--   user_id: The board account. NULL until one is made, and NULL again if it is
--     deleted: the registry entry is the machine's and outlives it.
--   settings: env, args, cliArgs, options, autoAllowTools, command,
--     terminalCommand, mcpServers. JSON on purpose: this is how to start
--     a process, it points at nothing and nothing joins to it.
CREATE UNIQUE INDEX "idx_{{.prefix}}agent_name" ON "{{.prefix}}agent" ("name");

-- A run of an agent over ACP. One process, one verdict: unlike a
-- conversation, it is never resumed, which is why the two are
-- separate tables and not one row with a transport column.
--   card_id: NULL for a run that is about no card — naming a branch is one.
--   finished_at: NULL means the session is still live.
CREATE TABLE "{{.prefix}}agent_session" ("id" character varying(36) NOT NULL, "card_id" character varying(36) NULL, "board_id" character varying(36) NULL, "agent_kind" character varying(32) NOT NULL, "acp_session_id" character varying(100) NULL, "status" character varying(24) NOT NULL, "cwd" text NULL, "worktree_path" text NULL, "branch" character varying(255) NULL, "started_at" bigint NOT NULL, "finished_at" bigint NULL, "error_text" text NULL, PRIMARY KEY ("id"), CONSTRAINT "agent_session_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE, CONSTRAINT "agent_session_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- A run of an agent over ACP. One process, one verdict: unlike a
-- conversation, it is never resumed, which is why the two are
-- separate tables and not one row with a transport column.
--   card_id: NULL for a run that is about no card — naming a branch is one.
--   finished_at: NULL means the session is still live.
CREATE INDEX "idx_{{.prefix}}agent_session_card" ON "{{.prefix}}agent_session" ("card_id", "started_at");

-- Which setup questions a board has been asked. It is about this machine
-- — the answers are folders and hosts here — so it cannot live in the
-- browser's storage, which the desktop window forgets on every launch.
--   changed_at: Was `at`. AT is a keyword in Postgres and a name not worth having.
CREATE TABLE "{{.prefix}}board_setup" ("board_id" character varying(36) NOT NULL, "step" character varying(32) NOT NULL, "status" character varying(16) NOT NULL, "changed_at" bigint NOT NULL, PRIMARY KEY ("board_id", "step"), CONSTRAINT "board_setup_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- One current reason a card is not moving — not a journal. The reason is
-- true only until somebody fixes what it is about, and a comment would
-- outlive it as noise.
--   kind: 'conversation' is the one kind with somewhere to go: open the
--     terminal. The rest have no button, which is why this is a field and
--     never a reading of the reason's own Russian.
CREATE TABLE "{{.prefix}}card_stall" ("card_id" character varying(36) NOT NULL, "node_id" character varying(64) NULL, "kind" character varying(32) NULL, "reason" text NOT NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("card_id"), CONSTRAINT "card_stall_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE);

-- A conversation with an agent: its CLI in a pty, keyed (card, node).
-- The row outlives every process that ever drew it — that is what makes
-- a conversation resumable, and it is the difference from agent_session,
-- which is one run and then over.
--   card_id: NULL for a planning conversation: it is about no card.
--   node_id: The column's option id — work; '@talk' — discussion; '@none' — a
--     card with no column at all.
--   column_name: What the column was called at the time, frozen: the option may be
--     gone, and the row still has to read the same.
--   summary: The agent's own line about what this conversation is doing.
--   workdir_path: Was repo_path. Becomes workspace_id in the second half of step 2,
--     together with the code that resolves a folder to its registry id.
CREATE TABLE "{{.prefix}}conversation" ("id" character varying(36) NOT NULL, "card_id" character varying(36) NULL, "board_id" character varying(36) NULL, "node_id" character varying(64) NOT NULL, "column_name" character varying(200) NULL, "title" text NULL, "summary" text NULL, "agent" character varying(100) NULL, "kind" character varying(32) NULL, "workdir_path" text NULL, "cwd" text NULL, "branch" character varying(255) NULL, "started_at" bigint NOT NULL, "ended_at" bigint NULL, "exit_code" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "conversation_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE, CONSTRAINT "conversation_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- A conversation with an agent: its CLI in a pty, keyed (card, node).
-- The row outlives every process that ever drew it — that is what makes
-- a conversation resumable, and it is the difference from agent_session,
-- which is one run and then over.
--   card_id: NULL for a planning conversation: it is about no card.
--   node_id: The column's option id — work; '@talk' — discussion; '@none' — a
--     card with no column at all.
--   column_name: What the column was called at the time, frozen: the option may be
--     gone, and the row still has to read the same.
--   summary: The agent's own line about what this conversation is doing.
--   workdir_path: Was repo_path. Becomes workspace_id in the second half of step 2,
--     together with the code that resolves a folder to its registry id.
CREATE INDEX "idx_{{.prefix}}conversation_card" ON "{{.prefix}}conversation" ("card_id", "started_at");

-- A conversation with an agent: its CLI in a pty, keyed (card, node).
-- The row outlives every process that ever drew it — that is what makes
-- a conversation resumable, and it is the difference from agent_session,
-- which is one run and then over.
--   card_id: NULL for a planning conversation: it is about no card.
--   node_id: The column's option id — work; '@talk' — discussion; '@none' — a
--     card with no column at all.
--   column_name: What the column was called at the time, frozen: the option may be
--     gone, and the row still has to read the same.
--   summary: The agent's own line about what this conversation is doing.
--   workdir_path: Was repo_path. Becomes workspace_id in the second half of step 2,
--     together with the code that resolves a folder to its registry id.
CREATE INDEX "idx_{{.prefix}}conversation_card_node" ON "{{.prefix}}conversation" ("card_id", "node_id", "started_at");

-- Every transition a card made, and what the agent said on it.
--   said: The agent's closing words: what a conversation is told instead of
--     its task when the card comes back to it.
CREATE TABLE "{{.prefix}}flow_event" ("id" character varying(36) NOT NULL, "card_id" character varying(36) NOT NULL, "flow" character varying(200) NOT NULL, "from_node" character varying(64) NULL, "to_node" character varying(64) NOT NULL, "on_kind" character varying(32) NOT NULL, "detail" text NULL, "said" text NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "flow_event_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE);

-- Every transition a card made, and what the agent said on it.
--   said: The agent's closing words: what a conversation is told instead of
--     its task when the card comes back to it.
CREATE INDEX "idx_{{.prefix}}flow_event_card" ON "{{.prefix}}flow_event" ("card_id", "id");

-- This machine's index of where each card is on its route. The truth is
-- on the card itself, so it travels with the board; this is what the VCS
-- watcher asks "which cards are parked and on what branch" in one query.
--   flow: The route's name. It has no id of its own yet — contradiction 4 of
--     docs/model-graph.md, which lives inside the board's JSON.
CREATE TABLE "{{.prefix}}flow_state" ("card_id" character varying(36) NOT NULL, "board_id" character varying(36) NULL, "flow" character varying(200) NOT NULL, "node_id" character varying(64) NOT NULL, "branch" character varying(255) NULL, "workdir_path" text NULL, "entered_at" bigint NOT NULL, PRIMARY KEY ("card_id"), CONSTRAINT "flow_state_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE, CONSTRAINT "flow_state_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- What happened during a session, in order. The id is a UUIDv7 rather
-- than an autoincrement: v7 sorts by time, so ORDER BY id still means
-- "as it happened" and the three spellings of AUTO_INCREMENT are gone.
-- `seq` went with them — it was the same fact told twice.
CREATE TABLE "{{.prefix}}session_event" ("id" character varying(36) NOT NULL, "session_id" character varying(36) NOT NULL, "kind" character varying(32) NOT NULL, "payload_json" text NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "session_event_session" FOREIGN KEY ("session_id") REFERENCES "{{.prefix}}agent_session" ("id") ON DELETE CASCADE);

-- What happened during a session, in order. The id is a UUIDv7 rather
-- than an autoincrement: v7 sorts by time, so ORDER BY id still means
-- "as it happened" and the three spellings of AUTO_INCREMENT are gone.
-- `seq` went with them — it was the same fact told twice.
CREATE INDEX "idx_{{.prefix}}session_event_session" ON "{{.prefix}}session_event" ("session_id", "id");

-- Why nothing happened — the only question anybody asks of a source.
-- Deleting the card it produced does not delete the line: what a source
-- decided is a fact about the source.
CREATE TABLE "{{.prefix}}source_event" ("id" character varying(36) NOT NULL, "source" character varying(100) NOT NULL, "external_id" character varying(255) NULL, "rule" character varying(100) NULL, "outcome" character varying(16) NOT NULL, "card_id" character varying(36) NULL, "detail" text NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "source_event_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE SET NULL);

-- Why nothing happened — the only question anybody asks of a source.
-- Deleting the card it produced does not delete the line: what a source
-- decided is a fact about the source.
CREATE INDEX "idx_{{.prefix}}source_event_source" ON "{{.prefix}}source_event" ("source", "id");

-- What a source has already brought. The same letter arriving twice adds
-- to the card it made rather than making a second one.
--   version: The service's own updated/etag: changed means there is something
--     to add.
CREATE TABLE "{{.prefix}}source_item" ("source" character varying(100) NOT NULL, "external_id" character varying(255) NOT NULL, "version" character varying(255) NULL, "card_id" character varying(36) NULL, "created_at" bigint NOT NULL, "updated_at" bigint NOT NULL, PRIMARY KEY ("source", "external_id"), CONSTRAINT "source_item_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE SET NULL);

-- What a source has already brought. The same letter arriving twice adds
-- to the card it made rather than making a second one.
--   version: The service's own updated/etag: changed means there is something
--     to add.
CREATE INDEX "idx_{{.prefix}}source_item_card" ON "{{.prefix}}source_item" ("card_id");

-- A card waiting for its column to free up a place.
--   column_key: board|option — the queue belongs to one column of one board.
CREATE TABLE "{{.prefix}}stage_queue" ("card_id" character varying(36) NOT NULL, "board_id" character varying(36) NULL, "column_key" character varying(128) NOT NULL, "flow" character varying(200) NULL, "node_id" character varying(64) NULL, "queued_at" bigint NOT NULL, PRIMARY KEY ("card_id"), CONSTRAINT "stage_queue_card" FOREIGN KEY ("card_id") REFERENCES "{{.prefix}}blocks" ("id") ON DELETE CASCADE, CONSTRAINT "stage_queue_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);

-- A card waiting for its column to free up a place.
--   column_key: board|option — the queue belongs to one column of one board.
CREATE INDEX "idx_{{.prefix}}stage_queue_column" ON "{{.prefix}}stage_queue" ("column_key", "queued_at");

-- A named place an agent can work in. Was the `projects` array in
-- config.json; a card points at it by id, which is also the id of the
-- board option offered for it, so a card naming its folder is a card
-- holding an ordinary select value that happens to be a reference.
--   name: A caption, not a key. Renaming it breaks nothing, which is the
--     whole reason the id exists.
--   board_id: The board that offers this folder, and the only one that does.
--     NULL means no board has claimed it — a state the product already
--     has a name and a screen for, which is why a deleted board sets this
--     to NULL rather than taking the registry entry with it.
--   global: «На всех досках»: one entry seen from several boards, which is what
--     makes the mode belong to the pair rather than to the folder.
--   kind: What somebody was promised, not what the folder happens to be:
--     'git' means a repository was demanded and one without git is an
--     error. NULL is the ordinary case and means nobody said.
CREATE TABLE "{{.prefix}}workspace" ("id" character varying(36) NOT NULL, "name" character varying(200) NOT NULL, "path" text NULL, "board_id" character varying(36) NULL, "global" boolean NOT NULL, "kind" character varying(16) NULL, "base_branch" character varying(200) NULL, "branch_prefix" character varying(64) NULL, "created_at" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "workspace_offered_on" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE SET NULL);

-- A named place an agent can work in. Was the `projects` array in
-- config.json; a card points at it by id, which is also the id of the
-- board option offered for it, so a card naming its folder is a card
-- holding an ordinary select value that happens to be a reference.
--   name: A caption, not a key. Renaming it breaks nothing, which is the
--     whole reason the id exists.
--   board_id: The board that offers this folder, and the only one that does.
--     NULL means no board has claimed it — a state the product already
--     has a name and a screen for, which is why a deleted board sets this
--     to NULL rather than taking the registry entry with it.
--   global: «На всех досках»: one entry seen from several boards, which is what
--     makes the mode belong to the pair rather than to the folder.
--   kind: What somebody was promised, not what the folder happens to be:
--     'git' means a repository was demanded and one without git is an
--     error. NULL is the ordinary case and means nobody said.
CREATE UNIQUE INDEX "idx_{{.prefix}}workspace_name" ON "{{.prefix}}workspace" ("name");

-- Which board a folder is offered to and how work happens in it there.
-- Keyed by the pair rather than by the folder, because a folder marked
-- «на всех досках» is one entry with a different answer per board: a copy
-- per card where three people work it, a branch in place where one does.
-- Was WorkdirEntry.Modes, a map keyed by board id.
--   mode: worktree | branch. NULL means nobody answered, and the machine's
--     own default stands in.
CREATE TABLE "{{.prefix}}workspace_board" ("workspace_id" character varying(36) NOT NULL, "board_id" character varying(36) NOT NULL, "mode" character varying(16) NULL, PRIMARY KEY ("workspace_id", "board_id"), CONSTRAINT "workspace_board_workspace" FOREIGN KEY ("workspace_id") REFERENCES "{{.prefix}}workspace" ("id") ON DELETE CASCADE, CONSTRAINT "workspace_board_board" FOREIGN KEY ("board_id") REFERENCES "{{.prefix}}boards" ("id") ON DELETE CASCADE);
{{end}}
