-- Generated by tools/schemagen. Do not edit by hand: change the schema there
-- and run `go generate ./tools/schemagen`.
--
-- The three dialects below say the same thing. Writing them by hand is what
-- eighty migrations of this fork do, and every one of them is a place where
-- somebody has to remember three answers to one question.

{{if .sqlite}}
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}source_event`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}source_item`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}workdir_claim`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}vcs_seen`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}board_setup`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}stage_queue`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}card_stall`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}flow_event`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}flow_state`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}idempotency`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}conversation`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}session_event`;
PRAGMA foreign_keys = on;
PRAGMA foreign_keys = off;
DROP TABLE `{{.prefix}}agent_session`;
PRAGMA foreign_keys = on;
{{end}}

{{if .mysql}}
DROP TABLE `{{.prefix}}source_event`;
DROP TABLE `{{.prefix}}source_item`;
DROP TABLE `{{.prefix}}workdir_claim`;
DROP TABLE `{{.prefix}}vcs_seen`;
DROP TABLE `{{.prefix}}board_setup`;
DROP TABLE `{{.prefix}}stage_queue`;
DROP TABLE `{{.prefix}}card_stall`;
DROP TABLE `{{.prefix}}flow_event`;
DROP TABLE `{{.prefix}}flow_state`;
DROP TABLE `{{.prefix}}idempotency`;
DROP TABLE `{{.prefix}}conversation`;
DROP TABLE `{{.prefix}}session_event`;
DROP TABLE `{{.prefix}}agent_session`;
{{end}}

{{if .postgres}}
DROP TABLE "{{.prefix}}source_event";
DROP TABLE "{{.prefix}}source_item";
DROP TABLE "{{.prefix}}workdir_claim";
DROP TABLE "{{.prefix}}vcs_seen";
DROP TABLE "{{.prefix}}board_setup";
DROP TABLE "{{.prefix}}stage_queue";
DROP TABLE "{{.prefix}}card_stall";
DROP TABLE "{{.prefix}}flow_event";
DROP TABLE "{{.prefix}}flow_state";
DROP TABLE "{{.prefix}}idempotency";
DROP TABLE "{{.prefix}}conversation";
DROP TABLE "{{.prefix}}session_event";
DROP TABLE "{{.prefix}}agent_session";
{{end}}
