// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/artipop/xciii/server/services/permissions (interfaces: PermissionsService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/artipop/xciii/server/model"
	gomock "github.com/golang/mock/gomock"
)

// MockPermissionsService is a mock of PermissionsService interface.
type MockPermissionsService struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionsServiceMockRecorder
}

// MockPermissionsServiceMockRecorder is the mock recorder for MockPermissionsService.
type MockPermissionsServiceMockRecorder struct {
	mock *MockPermissionsService
}

// NewMockPermissionsService creates a new mock instance.
func NewMockPermissionsService(ctrl *gomock.Controller) *MockPermissionsService {
	mock := &MockPermissionsService{ctrl: ctrl}
	mock.recorder = &MockPermissionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionsService) EXPECT() *MockPermissionsServiceMockRecorder {
	return m.recorder
}

// HasPermissionTo mocks base method.
func (m *MockPermissionsService) HasPermissionTo(arg0 string, arg1 *model.Permission) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermissionTo", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPermissionTo indicates an expected call of HasPermissionTo.
func (mr *MockPermissionsServiceMockRecorder) HasPermissionTo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermissionTo", reflect.TypeOf((*MockPermissionsService)(nil).HasPermissionTo), arg0, arg1)
}

// HasPermissionToBoard mocks base method.
func (m *MockPermissionsService) HasPermissionToBoard(arg0, arg1 string, arg2 *model.Permission) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermissionToBoard", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPermissionToBoard indicates an expected call of HasPermissionToBoard.
func (mr *MockPermissionsServiceMockRecorder) HasPermissionToBoard(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermissionToBoard", reflect.TypeOf((*MockPermissionsService)(nil).HasPermissionToBoard), arg0, arg1, arg2)
}

// HasPermissionToChannel mocks base method.
func (m *MockPermissionsService) HasPermissionToChannel(arg0, arg1 string, arg2 *model.Permission) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermissionToChannel", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPermissionToChannel indicates an expected call of HasPermissionToChannel.
func (mr *MockPermissionsServiceMockRecorder) HasPermissionToChannel(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermissionToChannel", reflect.TypeOf((*MockPermissionsService)(nil).HasPermissionToChannel), arg0, arg1, arg2)
}

// HasPermissionToTeam mocks base method.
func (m *MockPermissionsService) HasPermissionToTeam(arg0, arg1 string, arg2 *model.Permission) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermissionToTeam", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPermissionToTeam indicates an expected call of HasPermissionToTeam.
func (mr *MockPermissionsServiceMockRecorder) HasPermissionToTeam(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermissionToTeam", reflect.TypeOf((*MockPermissionsService)(nil).HasPermissionToTeam), arg0, arg1, arg2)
}
