package acp

import (
	"fmt"
	"strings"
)

// A flow is the route a card takes across the board: a graph of nodes (a column
// plus what runs when a card lands in it) and edges (which event moves the card
// on, and where). Several routes coexist — not every task is deployed — so a
// flow is a named registry entry a card is matched to, exactly like the project,
// agent and deploy-target registries.
//
// The set of edge triggers is closed and implemented in Go (see FlowTriggers):
// the graph says *what* connects to what, the code decides *when*. Nothing in
// the config is interpreted as a script.

// Node actions: what runs when a card enters the node.
const (
	FlowActionNone   = "none"   // nothing runs; the card waits for an event
	FlowActionAgent  = "agent"  // an ordinary agent session on the card task
	FlowActionDeploy = "deploy" // a deploy session (Dokku)
	FlowActionTest   = "test"   // a browser test session against the preview
)

// Edge triggers. The outcome ones are produced by the node's own action; the
// rest come from the VCS watcher.
const (
	TriggerSuccess = "success"
	TriggerFailure = "failure"
	TriggerBlocked = "blocked"

	TriggerBranchPushed = "branch.pushed"
	TriggerBranchMerged = "branch.merged"

	TriggerPROpened       = "pr.opened"
	TriggerPRMerged       = "pr.merged"
	TriggerPRClosed       = "pr.closed"
	TriggerReviewApproved = "review.approved"
	TriggerChecksPassed   = "checks.passed"
	TriggerChecksFailed   = "checks.failed"
)

// Trigger sources, which decide who can produce an event and what the watcher
// has to poll for.
const (
	SourceOutcome = "outcome" // the node's own action finished
	SourceGit     = "git"     // local project, no authentication
	SourceGitHub  = "github"  // GitHub API, needs a token for private projects
)

// FlowTrigger describes one edge trigger. The list doubles as the editor's
// dropdown, so the UI can never offer a trigger the engine does not implement.
type FlowTrigger struct {
	Kind   string `json:"kind"`
	Source string `json:"source"`
	Label  string `json:"label"`
}

// FlowTriggers is the closed set, in the order the editor shows them.
var FlowTriggers = []FlowTrigger{
	{Kind: TriggerSuccess, Source: SourceOutcome, Label: "шаг прошёл"},
	{Kind: TriggerFailure, Source: SourceOutcome, Label: "шаг упал"},
	{Kind: TriggerBlocked, Source: SourceOutcome, Label: "проверить не удалось"},
	{Kind: TriggerBranchPushed, Source: SourceGit, Label: "ветка запушена"},
	{Kind: TriggerBranchMerged, Source: SourceGit, Label: "ветка влита в основную"},
	{Kind: TriggerPROpened, Source: SourceGitHub, Label: "открыт pull request"},
	{Kind: TriggerPRMerged, Source: SourceGitHub, Label: "pull request смержен"},
	{Kind: TriggerPRClosed, Source: SourceGitHub, Label: "pull request закрыт"},
	{Kind: TriggerReviewApproved, Source: SourceGitHub, Label: "ревью одобрено"},
	{Kind: TriggerChecksPassed, Source: SourceGitHub, Label: "проверки прошли"},
	{Kind: TriggerChecksFailed, Source: SourceGitHub, Label: "проверки упали"},
}

// FlowEntry is one named route in the registry.
type FlowEntry struct {
	Name string `json:"name"` // registry key; matches the card "Flow" option

	// BoardID is the board the route belongs to. A route that came from a
	// board's own settings carries it, so two boards can hold routes of the
	// same name and not see each other's. Empty means every board, which is
	// what a route configured before boards were told apart means.
	BoardID string `json:"boardId,omitempty"`

	// ProjectName ties the flow to an entry of the project registry, so a card that
	// only names its project still finds its route.
	ProjectName string `json:"projectName,omitempty"`
	// Property is the select property whose options are the flow's columns.
	// Empty means Config.TriggerProperty.
	Property string `json:"property,omitempty"`

	Nodes []FlowNode `json:"nodes"`
	Edges []FlowEdge `json:"edges"`
}

// FlowNode is one stage of a route: the column a card stands in. What happens
// there is the column's business (see columns.go) — a stage only overrides what
// it names itself, which is how one column can behave differently in two routes.
type FlowNode struct {
	ID       string `json:"id"`                 // stable identifier, generated by the editor
	Column   string `json:"column"`             // option name on the board
	OptionID string `json:"optionId,omitempty"` // the option itself, so a rename changes nothing

	// Action overrides the column's. Empty means "whatever the column does";
	// "none" means the stage runs nothing and waits for an event.
	Action string `json:"action,omitempty"`

	// AgentNames is the crew for this stage alone, overriding the column's.
	AgentNames []string `json:"agentNames,omitempty"`
	// AgentName is what a single-agent stage used to be called. Read on load
	// and folded into AgentNames; never written back.
	AgentName string `json:"agentName,omitempty"`

	// DeployName overrides the column's deploy target for this stage.
	DeployName string `json:"deployName,omitempty"`

	// X and Y are where the builder left the stage on its canvas. Absent means
	// "lay it out for me" — a route written by hand never has to place anything.
	X float64 `json:"x,omitempty"`
	Y float64 `json:"y,omitempty"`
}

// Crew is the agents this stage may run on, if it names any.
func (n FlowNode) Crew() []string {
	if len(n.AgentNames) > 0 {
		return n.AgentNames
	}
	if n.AgentName != "" {
		return []string{n.AgentName}
	}
	return nil
}

// asColumn is the stage's column in the shape the column registry matches.
func (n FlowNode) asColumn(property string) Column {
	return Column{PropertyName: property, Name: n.Column, OptionID: n.OptionID}
}

// FlowEdge is one transition. On is a FlowTrigger kind; success/failure are the
// node's own outcomes, which the editor shows as the node's two outputs.
type FlowEdge struct {
	From string `json:"from"`
	To   string `json:"to"`
	On   string `json:"on"`
}

// Trigger looks a trigger kind up in the closed set.
func Trigger(kind string) (FlowTrigger, bool) {
	for _, t := range FlowTriggers {
		if t.Kind == kind {
			return t, true
		}
	}
	return FlowTrigger{}, false
}

// TriggerLabel is the human phrasing used in card comments.
func TriggerLabel(kind string) string {
	if t, ok := Trigger(kind); ok {
		return t.Label
	}
	return kind
}

// IsVCSTrigger reports whether the trigger comes from the project rather
// than from the node's own action — the ones the watcher has to poll for.
func IsVCSTrigger(kind string) bool {
	t, ok := Trigger(kind)
	return ok && t.Source != SourceOutcome
}

// IsGitHubTrigger reports whether the trigger needs the GitHub API.
func IsGitHubTrigger(kind string) bool {
	t, ok := Trigger(kind)
	return ok && t.Source == SourceGitHub
}

// Node returns the node with the given id.
func (f FlowEntry) Node(id string) (FlowNode, bool) {
	for _, n := range f.Nodes {
		if n.ID == id {
			return n, true
		}
	}
	return FlowNode{}, false
}

// NodeByColumn returns the node sitting on a column, matched the way every
// other column comparison in the package is: case-insensitively.
func (f FlowEntry) NodeByColumn(column string) (FlowNode, bool) {
	column = strings.TrimSpace(column)
	if column == "" {
		return FlowNode{}, false
	}
	for _, n := range f.Nodes {
		if strings.EqualFold(n.Column, column) {
			return n, true
		}
	}
	return FlowNode{}, false
}

// Next returns the node an event moves the card to.
func (f FlowEntry) Next(nodeID, on string) (FlowNode, bool) {
	for _, e := range f.Edges {
		if e.From == nodeID && e.On == on {
			return f.Node(e.To)
		}
	}
	return FlowNode{}, false
}

// WaitsFor lists the VCS triggers a node has edges for. An empty result means
// the card parked on this node needs no polling at all.
func (f FlowEntry) WaitsFor(nodeID string) []string {
	var out []string
	for _, e := range f.Edges {
		if e.From == nodeID && IsVCSTrigger(e.On) {
			out = append(out, e.On)
		}
	}
	return out
}

// PropertyOr returns the select property the flow's columns belong to.
func (f FlowEntry) PropertyOr(fallback string) string {
	if p := strings.TrimSpace(f.Property); p != "" {
		return p
	}
	return fallback
}

// Flows returns a snapshot of the registry.
func (m *Manager) Flows() []FlowEntry {
	m.cfgMu.RLock()
	defer m.cfgMu.RUnlock()
	return append([]FlowEntry(nil), m.cfg.Flows...)
}

// BoardFlows returns the routes a board may use: its own, plus those tied to no
// board in particular. It is what the editor lists, so one board never offers
// another's routes.
func (m *Manager) BoardFlows(boardID string) []FlowEntry {
	m.cfgMu.RLock()
	defer m.cfgMu.RUnlock()
	return boardFlows(m.cfg.Flows, boardID)
}

func boardFlows(flows []FlowEntry, boardID string) []FlowEntry {
	out := make([]FlowEntry, 0, len(flows))
	for _, f := range flows {
		if f.BoardID == "" || boardID == "" || f.BoardID == boardID {
			out = append(out, f)
		}
	}
	return out
}

// validateFlow normalizes and checks one route. projects/agents/deploys are the
// registries its nodes may reference.
func validateFlow(f FlowEntry, projects []ProjectEntry, agents []AgentEntry, deploys []DeployEntry) (FlowEntry, error) {
	f.Name = strings.TrimSpace(f.Name)
	if f.Name == "" {
		return FlowEntry{}, fmt.Errorf("имя флоу не может быть пустым")
	}
	f.ProjectName = strings.TrimSpace(f.ProjectName)
	if f.ProjectName != "" && !hasRepo(projects, f.ProjectName) {
		return FlowEntry{}, fmt.Errorf("проект %q не найден в реестре (%s)", f.ProjectName, projectNames(projects))
	}
	f.Property = strings.TrimSpace(f.Property)
	if len(f.Nodes) == 0 {
		return FlowEntry{}, fmt.Errorf("флоу %q не содержит ни одной стадии", f.Name)
	}

	seenID := make(map[string]bool, len(f.Nodes))
	seenColumn := make(map[string]bool, len(f.Nodes))
	for i, n := range f.Nodes {
		n.ID = strings.TrimSpace(n.ID)
		n.Column = strings.TrimSpace(n.Column)
		// An empty action is not "nothing": it means the stage does whatever
		// its column does. "none" is how a stage says it runs nothing at all.
		n.Action = strings.TrimSpace(n.Action)
		if n.ID == "" {
			return FlowEntry{}, fmt.Errorf("у стадии %d нет идентификатора", i+1)
		}
		if seenID[n.ID] {
			return FlowEntry{}, fmt.Errorf("идентификатор стадии %q встречается дважды", n.ID)
		}
		if n.Column == "" {
			return FlowEntry{}, fmt.Errorf("у стадии %q не выбрана колонка", n.ID)
		}
		lower := strings.ToLower(n.Column)
		if seenColumn[lower] {
			return FlowEntry{}, fmt.Errorf("колонка %q занята двумя стадиями — карточка не сможет понять, где она", n.Column)
		}
		switch n.Action {
		case "", FlowActionNone, FlowActionAgent, FlowActionDeploy, FlowActionTest:
		default:
			return FlowEntry{}, fmt.Errorf("неизвестное действие %q у стадии %q", n.Action, n.ID)
		}

		// A stage written before crews existed named one agent; fold it in and
		// stop writing the old field.
		crew := n.AgentNames
		if name := strings.TrimSpace(n.AgentName); name != "" {
			crew = append([]string{name}, crew...)
		}
		n.AgentName, n.AgentNames = "", nil
		seenAgent := make(map[string]bool, len(crew))
		for _, name := range crew {
			name = strings.TrimSpace(name)
			if name == "" || seenAgent[strings.ToLower(name)] {
				continue
			}
			if !hasAgent(agents, name) {
				return FlowEntry{}, fmt.Errorf("агент %q стадии %q не найден в реестре (%s)", name, n.ID, agentNames(agents))
			}
			seenAgent[strings.ToLower(name)] = true
			n.AgentNames = append(n.AgentNames, name)
		}
		n.DeployName = strings.TrimSpace(n.DeployName)
		if n.DeployName != "" && !hasDeploy(deploys, n.DeployName) {
			return FlowEntry{}, fmt.Errorf("цель деплоя %q стадии %q не найдена в реестре (%s)", n.DeployName, n.ID, deployNames(deploys))
		}
		seenID[n.ID] = true
		seenColumn[lower] = true
		f.Nodes[i] = n
	}

	seenEdge := make(map[string]bool, len(f.Edges))
	for i, e := range f.Edges {
		e.From = strings.TrimSpace(e.From)
		e.To = strings.TrimSpace(e.To)
		e.On = strings.TrimSpace(e.On)
		if !seenID[e.From] {
			return FlowEntry{}, fmt.Errorf("переход ведёт из несуществующей стадии %q", e.From)
		}
		if !seenID[e.To] {
			return FlowEntry{}, fmt.Errorf("переход из %q ведёт в несуществующую стадию %q", e.From, e.To)
		}
		if _, ok := Trigger(e.On); !ok {
			return FlowEntry{}, fmt.Errorf("неизвестное событие перехода %q", e.On)
		}
		key := e.From + "|" + e.On
		if seenEdge[key] {
			return FlowEntry{}, fmt.Errorf("у стадии %q два перехода по событию %q — куда ехать, непонятно", e.From, TriggerLabel(e.On))
		}
		seenEdge[key] = true
		f.Edges[i] = e
	}
	return f, nil
}

// AddFlow registers a new route and persists the config.
func (m *Manager) AddFlow(f FlowEntry) (FlowEntry, error) {
	m.cfgMu.Lock()
	defer m.cfgMu.Unlock()
	f, err := validateFlow(f, m.cfg.Projects, m.cfg.Agents, m.cfg.Deploys)
	if err != nil {
		return FlowEntry{}, err
	}
	for _, e := range m.cfg.Flows {
		if strings.EqualFold(e.Name, f.Name) {
			return FlowEntry{}, fmt.Errorf("флоу с именем %q уже существует", e.Name)
		}
	}
	m.cfg.Flows = append(m.cfg.Flows, f)
	return f, m.persistConfigLocked()
}

// UpdateFlow replaces an existing route (matched by name) and persists.
func (m *Manager) UpdateFlow(f FlowEntry) (FlowEntry, error) {
	m.cfgMu.Lock()
	defer m.cfgMu.Unlock()
	f, err := validateFlow(f, m.cfg.Projects, m.cfg.Agents, m.cfg.Deploys)
	if err != nil {
		return FlowEntry{}, err
	}
	for i, e := range m.cfg.Flows {
		if strings.EqualFold(e.Name, f.Name) {
			m.cfg.Flows[i] = f
			return f, m.persistConfigLocked()
		}
	}
	return FlowEntry{}, fmt.Errorf("флоу %q не найден", f.Name)
}

// RemoveFlow deletes a route by name and persists. Cards currently on it stop
// moving by themselves; nothing else happens to them.
func (m *Manager) RemoveFlow(name string) error {
	m.cfgMu.Lock()
	defer m.cfgMu.Unlock()
	for i, e := range m.cfg.Flows {
		if strings.EqualFold(e.Name, name) {
			m.cfg.Flows = append(m.cfg.Flows[:i], m.cfg.Flows[i+1:]...)
			return m.persistConfigLocked()
		}
	}
	return fmt.Errorf("флоу %q не найден", name)
}

// resolveFlow maps a card to its route. Priority mirrors every other registry:
//  1. a "flow" property or a select option naming an entry;
//  2. the flow tied to the project the card resolved to;
//  3. the single registered flow.
//
// Nothing matched is not an error: the card simply has no route, and the legacy
// trigger columns keep working for it.
func (m *Manager) resolveFlow(ev CardMoved, projectPath string) *FlowEntry {
	m.cfgMu.RLock()
	flows := boardFlows(m.cfg.Flows, ev.BoardID)
	projects := append([]ProjectEntry(nil), m.cfg.Projects...)
	m.cfgMu.RUnlock()

	if len(flows) == 0 {
		return nil
	}
	find := func(name string) *FlowEntry {
		for i := range flows {
			if strings.EqualFold(strings.TrimSpace(name), flows[i].Name) {
				return &flows[i]
			}
		}
		return nil
	}
	if explicit := strings.TrimSpace(ev.Props["flow"]); explicit != "" {
		if f := find(explicit); f != nil {
			return f
		}
	}
	for _, opt := range ev.OptionNames {
		if f := find(opt); f != nil {
			return f
		}
	}
	if projectName := rrojectNameForPath(projects, projectPath); projectName != "" {
		for i := range flows {
			if strings.EqualFold(flows[i].ProjectName, projectName) {
				return &flows[i]
			}
		}
	}
	if len(flows) == 1 {
		return &flows[0]
	}
	return nil
}

// FlowByName returns a registered route.
func (m *Manager) FlowByName(name string) (FlowEntry, bool) {
	m.cfgMu.RLock()
	defer m.cfgMu.RUnlock()
	for _, f := range m.cfg.Flows {
		if strings.EqualFold(f.Name, name) {
			return f, true
		}
	}
	return FlowEntry{}, false
}

func hasRepo(projects []ProjectEntry, name string) bool {
	for _, r := range projects {
		if strings.EqualFold(r.Name, name) {
			return true
		}
	}
	return false
}

func hasAgent(agents []AgentEntry, name string) bool {
	for _, a := range agents {
		if strings.EqualFold(a.Name, name) {
			return true
		}
	}
	return false
}

func hasDeploy(deploys []DeployEntry, name string) bool {
	for _, d := range deploys {
		if strings.EqualFold(d.Name, name) {
			return true
		}
	}
	return false
}
