package main

import (
	"fmt"

	"ariga.io/atlas/sql/sqlite"
)

// The schema as Atlas HCL, for anybody who wants to point Atlas's own tooling
// at it — a diff against a live database, a lint, a visualisation.
//
// Generated rather than written, which is the difference from the file that
// used to stand here: docs/schema/app.hcl was a hand-written picture of where
// the store work was going, and by the time the work arrived it described a
// schema with the registries still in config.json and a table called
// workdir_claim. A snapshot for reading is worth having; a snapshot somebody
// maintains by hand is a second source of truth.
//
// SQLite, because that is what the application runs on. What the other two
// dialects change is types alone, and the migration itself carries all three.
func renderHCL() (string, error) {
	s, err := build(dialects()[0], append(boardTables(), appTables()...))
	if err != nil {
		return "", err
	}
	out, err := sqlite.MarshalHCL(s)
	if err != nil {
		return "", fmt.Errorf("rendering HCL: %w", err)
	}
	return hclHeader + string(out), nil
}

const hclHeader = `// Generated by tools/schemagen. Do not edit by hand: change the schema there
// and run ` + "`go generate ./tools/schemagen`" + `.
//
// The whole database as Atlas HCL — the fork's tables and this application's,
// in the dialect the application runs on. It is a rendering for reading and for
// Atlas's own tooling, not the source: the source is Go data in
// tools/schemagen, and what actually creates the database is the migration
// beside it.
//
// Drawn instead: docs/schema/erd.md.

`
