package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

//go:generate go run . -write

// migrationsDir is where the board's migration ladder lives, relative to the
// module root. Ours is a rung on it rather than a ladder of its own: one
// database, one engine, one version.
const migrationsDir = "server/services/store/sqlstore/migrations"

// migrationName is the whole schema, in one step. It was rung 41 on a ladder of
// eighty-one files; the ladder is gone (docs/store-plan.md, step 0), because
// every step of it led to this same schema and none of them means anything to a
// database being created now.
//
// What made that safe to do is that the result is checkable: `go run
// ./tools/schemagen -collapsed-sqlite` prints this schema as plain SQLite DDL,
// and it compares equal — table, column, key and index — to a database the
// eighty-one migrations built. See the test.
const migrationName = "000001_init"

func main() {
	write := flag.Bool("write", false, "write the migration files instead of printing them")
	collapsed := flag.Bool("collapsed-sqlite", false,
		"print the whole schema — the fork's tables and ours — as plain SQLite DDL, "+
			"for diffing against a database the migrations built")
	erd := flag.Bool("erd", false, "print the schema as a mermaid ER diagram")
	flag.Parse()

	if *erd {
		fmt.Print(renderERDDoc())
		return
	}

	if *collapsed {
		sql, err := renderUp(dialects()[0], append(boardTables(), appTables()...))
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Print(sql)
		return
	}

	up, down, err := render()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if !*write {
		fmt.Print(up)
		return
	}
	root, err := moduleRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	dir := filepath.Join(root, migrationsDir)
	for name, body := range map[string]string{
		migrationName + ".up.sql":   up,
		migrationName + ".down.sql": down,
	} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
	// The diagram and the HCL are generated beside the SQL rather than by a
	// second command, because a picture nobody remembers to regenerate is a
	// wrong picture.
	if err := os.WriteFile(filepath.Join(root, erdPath), []byte(renderERDDoc()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	hcl, err := renderHCL()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(root, hclPath), []byte(hcl), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

const (
	// erdPath is the schema drawn, and hclPath the same schema as Atlas HCL,
	// both relative to the module root.
	erdPath = "docs/schema/erd.md"
	hclPath = "docs/schema/app.hcl"
)

// moduleRoot walks up from the working directory to the go.mod, so the
// generator writes to the same place whether it was run by `go generate` from
// its own directory or by `go run ./tools/schemagen` from the root.
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod above %s", dir)
		}
		dir = parent
	}
}

// header is what anybody who opens the SQL reads first, because the SQL is the
// file a reviewer sees in the diff and the one a migration failure names.
const header = `-- Generated by tools/schemagen. Do not edit by hand: change the schema there
-- and run ` + "`go generate ./tools/schemagen`" + `.
--
-- The three dialects below say the same thing. Writing them by hand is what
-- eighty migrations of this fork do, and every one of them is a place where
-- somebody has to remember three answers to one question.
`

// render builds both halves of the migration: every dialect's DDL, each behind
// the condition golang-migrate's template already understands.
func render() (up, down string, err error) {
	// The fork's tables first: MySQL wants a foreign key's target to exist by
	// the time the key is written, and ours point at blocks, boards and users.
	tables := append(boardTables(), appTables()...)
	var ub, db strings.Builder
	ub.WriteString(header)
	db.WriteString(header)
	for _, d := range dialects() {
		body, err := renderUp(d, tables)
		if err != nil {
			return "", "", err
		}
		ub.WriteString(section(d.name, body))

		body, err = renderDown(d, tables)
		if err != nil {
			return "", "", err
		}
		db.WriteString(section(d.name, body))
	}
	return ub.String(), db.String(), nil
}

func section(name, body string) string {
	return "\n{{if ." + name + "}}\n" + strings.TrimRight(body, "\n") + "\n{{end}}\n"
}
