// Generated by tools/schemagen. Do not edit by hand: change the schema there
// and run `go generate ./tools/schemagen`.
//
// The whole database as Atlas HCL — the fork's tables and this application's,
// in the dialect the application runs on. It is a rendering for reading and for
// Atlas's own tooling, not the source: the source is Go data in
// tools/schemagen, and what actually creates the database is the migration
// beside it.
//
// Drawn instead: docs/schema/erd.md.

table "users" {
  column "id" {
    null = true
    type = varchar(100)
  }
  column "username" {
    null = true
    type = varchar(100)
  }
  column "email" {
    null = true
    type = varchar(255)
  }
  column "password" {
    null = true
    type = varchar(100)
  }
  column "mfa_secret" {
    null = true
    type = varchar(100)
  }
  column "auth_service" {
    null = true
    type = varchar(20)
  }
  column "auth_data" {
    null = true
    type = varchar(255)
  }
  column "props" {
    null = true
    type = text
  }
  column "create_at" {
    null = true
    type = bigint
  }
  column "update_at" {
    null = true
    type = bigint
  }
  column "delete_at" {
    null = true
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
}
table "teams" {
  column "id" {
    null = true
    type = varchar(36)
  }
  column "signup_token" {
    null = false
    type = varchar(100)
  }
  column "settings" {
    null = true
    type = text
  }
  column "modified_by" {
    null = true
    type = varchar(36)
  }
  column "update_at" {
    null = true
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
}
table "sessions" {
  column "id" {
    null = true
    type = varchar(100)
  }
  column "token" {
    null = true
    type = varchar(100)
  }
  column "user_id" {
    null = true
    type = varchar(100)
  }
  column "props" {
    null = true
    type = text
  }
  column "create_at" {
    null = true
    type = bigint
  }
  column "update_at" {
    null = true
    type = bigint
  }
  column "auth_service" {
    null = true
    type = varchar(20)
  }
  primary_key {
    columns = [column.id]
  }
}
table "system_settings" {
  column "id" {
    null = true
    type = varchar(100)
  }
  column "value" {
    null = true
    type = text
  }
  primary_key {
    columns = [column.id]
  }
}
table "boards" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "insert_at" {
    null    = false
    type    = datetime
    default = sql("STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')")
  }
  column "team_id" {
    null = false
    type = varchar(36)
  }
  column "channel_id" {
    null = true
    type = varchar(36)
  }
  column "created_by" {
    null = true
    type = varchar(36)
  }
  column "modified_by" {
    null = true
    type = varchar(36)
  }
  column "type" {
    null = false
    type = varchar(1)
  }
  column "title" {
    null = false
    type = text
  }
  column "description" {
    null = true
    type = text
  }
  column "icon" {
    null = true
    type = varchar(256)
  }
  column "show_description" {
    null = true
    type = boolean
  }
  column "is_template" {
    null = true
    type = boolean
  }
  column "template_version" {
    null    = true
    type    = int
    default = sql("0")
  }
  column "properties" {
    null = true
    type = text
  }
  column "card_properties" {
    null = true
    type = text
  }
  column "create_at" {
    null = true
    type = bigint
  }
  column "update_at" {
    null = true
    type = bigint
  }
  column "delete_at" {
    null = true
    type = bigint
  }
  column "minimum_role" {
    null    = false
    type    = varchar(36)
    default = sql("''")
  }
  primary_key {
    columns = [column.id]
  }
  index "idx_boards_team_id_is_template" {
    columns = [column.team_id, column.is_template]
  }
  index "idx_boards_channel_id" {
    columns = [column.channel_id]
  }
}
table "boards_history" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "insert_at" {
    null    = false
    type    = datetime
    default = sql("STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')")
  }
  column "team_id" {
    null = false
    type = varchar(36)
  }
  column "channel_id" {
    null = true
    type = varchar(36)
  }
  column "created_by" {
    null = true
    type = varchar(36)
  }
  column "modified_by" {
    null = true
    type = varchar(36)
  }
  column "type" {
    null = false
    type = varchar(1)
  }
  column "title" {
    null = false
    type = text
  }
  column "description" {
    null = true
    type = text
  }
  column "icon" {
    null = true
    type = varchar(256)
  }
  column "show_description" {
    null = true
    type = boolean
  }
  column "is_template" {
    null = true
    type = boolean
  }
  column "template_version" {
    null    = true
    type    = int
    default = sql("0")
  }
  column "properties" {
    null = true
    type = text
  }
  column "card_properties" {
    null = true
    type = text
  }
  column "create_at" {
    null = true
    type = bigint
  }
  column "update_at" {
    null = true
    type = bigint
  }
  column "delete_at" {
    null = true
    type = bigint
  }
  column "minimum_role" {
    null    = false
    type    = varchar(36)
    default = sql("''")
  }
  primary_key {
    columns = [column.id, column.insert_at]
  }
}
table "blocks" {
  column "id" {
    null = true
    type = varchar(36)
  }
  column "insert_at" {
    null    = false
    type    = datetime
    default = sql("STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')")
  }
  column "parent_id" {
    null = true
    type = varchar(36)
  }
  column "schema" {
    null = true
    type = bigint
  }
  column "type" {
    null = true
    type = text
  }
  column "title" {
    null = true
    type = text
  }
  column "fields" {
    null = true
    type = text
  }
  column "create_at" {
    null = true
    type = bigint
  }
  column "update_at" {
    null = true
    type = bigint
  }
  column "delete_at" {
    null = true
    type = bigint
  }
  column "modified_by" {
    null = true
    type = varchar(36)
  }
  column "channel_id" {
    null = true
    type = varchar(36)
  }
  column "created_by" {
    null = true
    type = varchar(36)
  }
  column "board_id" {
    null = true
    type = varchar(36)
  }
  primary_key {
    columns = [column.id]
  }
  index "idx_blocks_board_id_parent_id" {
    columns = [column.board_id, column.parent_id]
  }
}
table "blocks_history" {
  column "id" {
    null = true
    type = varchar(36)
  }
  column "insert_at" {
    null    = false
    type    = datetime
    default = sql("STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')")
  }
  column "parent_id" {
    null = true
    type = varchar(36)
  }
  column "schema" {
    null = true
    type = bigint
  }
  column "type" {
    null = true
    type = text
  }
  column "title" {
    null = true
    type = text
  }
  column "fields" {
    null = true
    type = text
  }
  column "create_at" {
    null = true
    type = bigint
  }
  column "update_at" {
    null = true
    type = bigint
  }
  column "delete_at" {
    null = true
    type = bigint
  }
  column "modified_by" {
    null = true
    type = varchar(36)
  }
  column "channel_id" {
    null = true
    type = varchar(36)
  }
  column "created_by" {
    null = true
    type = varchar(36)
  }
  column "board_id" {
    null = true
    type = varchar(36)
  }
  primary_key {
    columns = [column.id, column.insert_at]
  }
}
table "board_members" {
  column "board_id" {
    null = false
    type = varchar(36)
  }
  column "user_id" {
    null = false
    type = varchar(36)
  }
  column "roles" {
    null = true
    type = varchar(64)
  }
  column "scheme_admin" {
    null = true
    type = boolean
  }
  column "scheme_editor" {
    null = true
    type = boolean
  }
  column "scheme_commenter" {
    null = true
    type = boolean
  }
  column "scheme_viewer" {
    null = true
    type = boolean
  }
  primary_key {
    columns = [column.board_id, column.user_id]
  }
  index "idx_board_members_user_id" {
    columns = [column.user_id]
  }
}
table "board_members_history" {
  column "board_id" {
    null = false
    type = varchar(36)
  }
  column "user_id" {
    null = false
    type = varchar(36)
  }
  column "action" {
    null = true
    type = varchar(10)
  }
  column "insert_at" {
    null    = false
    type    = datetime
    default = sql("STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')")
  }
  primary_key {
    columns = [column.board_id, column.user_id, column.insert_at]
  }
  index "idx_board_members_history_user_id" {
    columns = [column.user_id]
  }
  index "idx_board_members_history_board_id_user_id" {
    columns = [column.board_id, column.user_id]
  }
}
table "categories" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "name" {
    null = false
    type = varchar(100)
  }
  column "user_id" {
    null = false
    type = varchar(36)
  }
  column "team_id" {
    null = false
    type = varchar(36)
  }
  column "channel_id" {
    null = true
    type = varchar(36)
  }
  column "create_at" {
    null = true
    type = bigint
  }
  column "update_at" {
    null = true
    type = bigint
  }
  column "delete_at" {
    null = true
    type = bigint
  }
  column "collapsed" {
    null    = true
    type    = boolean
    default = sql("false")
  }
  column "type" {
    null = true
    type = varchar(64)
  }
  column "sort_order" {
    null = true
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  index "idx_categories_user_id_team_id" {
    columns = [column.user_id, column.team_id]
  }
}
table "category_boards" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "user_id" {
    null = false
    type = varchar(36)
  }
  column "category_id" {
    null = false
    type = varchar(36)
  }
  column "board_id" {
    null = false
    type = varchar(36)
  }
  column "create_at" {
    null = true
    type = bigint
  }
  column "update_at" {
    null = true
    type = bigint
  }
  column "sort_order" {
    null = true
    type = bigint
  }
  column "hidden" {
    null = true
    type = boolean
  }
  primary_key {
    columns = [column.id]
  }
  index "unique_user_category_board" {
    unique  = true
    columns = [column.user_id, column.board_id]
  }
}
table "sharing" {
  column "id" {
    null = true
    type = varchar(36)
  }
  column "enabled" {
    null = true
    type = boolean
  }
  column "token" {
    null = true
    type = varchar(100)
  }
  column "modified_by" {
    null = true
    type = varchar(36)
  }
  column "update_at" {
    null = true
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
}
table "file_info" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "create_at" {
    null = false
    type = bigint
  }
  column "delete_at" {
    null = true
    type = bigint
  }
  column "name" {
    null = false
    type = text
  }
  column "extension" {
    null = false
    type = varchar(50)
  }
  column "size" {
    null = false
    type = bigint
  }
  column "archived" {
    null = true
    type = boolean
  }
  column "path" {
    null = true
    type = varchar(512)
  }
}
table "preferences" {
  column "userid" {
    null = false
    type = varchar(36)
  }
  column "category" {
    null = false
    type = varchar(32)
  }
  column "name" {
    null = false
    type = varchar(32)
  }
  column "value" {
    null = true
    type = text
  }
  primary_key {
    columns = [column.userid, column.category, column.name]
  }
  index "idx_preferences_category" {
    columns = [column.category]
  }
  index "idx_preferences_name" {
    columns = [column.name]
  }
}
table "subscriptions" {
  column "block_type" {
    null = true
    type = varchar(10)
  }
  column "block_id" {
    null = true
    type = varchar(36)
  }
  column "subscriber_type" {
    null = true
    type = varchar(10)
  }
  column "subscriber_id" {
    null = true
    type = varchar(36)
  }
  column "notified_at" {
    null = true
    type = bigint
  }
  column "create_at" {
    null = true
    type = bigint
  }
  column "delete_at" {
    null = true
    type = bigint
  }
  primary_key {
    columns = [column.block_id, column.subscriber_id]
  }
  index "idx_subscriptions_subscriber_id" {
    columns = [column.subscriber_id]
  }
}
table "notification_hints" {
  column "block_type" {
    null = true
    type = varchar(10)
  }
  column "block_id" {
    null = true
    type = varchar(36)
  }
  column "modified_by_id" {
    null = true
    type = varchar(36)
  }
  column "create_at" {
    null = true
    type = bigint
  }
  column "notify_at" {
    null = true
    type = bigint
  }
  primary_key {
    columns = [column.block_id]
  }
}
table "proxy" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "name" {
    null = false
    type = varchar(100)
  }
  column "url" {
    null = true
    type = text
  }
  column "no_proxy" {
    null = true
    type = text
  }
  column "ca_cert" {
    null = true
    type = text
  }
  column "username" {
    null = true
    type = varchar(100)
  }
  column "password" {
    null = true
    type = text
  }
  column "created_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  index "idx_proxy_name" {
    unique  = true
    columns = [column.name]
  }
}
table "workspace" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "name" {
    null = false
    type = varchar(200)
  }
  column "path" {
    null = true
    type = text
  }
  column "board_id" {
    null = true
    type = varchar(36)
  }
  column "global" {
    null = false
    type = boolean
  }
  column "kind" {
    null = true
    type = varchar(16)
  }
  column "base_branch" {
    null = true
    type = varchar(200)
  }
  column "branch_prefix" {
    null = true
    type = varchar(64)
  }
  column "created_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  foreign_key "workspace_offered_on" {
    columns     = [column.board_id]
    ref_columns = [table.boards.column.id]
    on_delete   = SET_NULL
  }
  index "idx_workspace_name" {
    unique  = true
    columns = [column.name]
  }
}
table "workspace_board" {
  column "workspace_id" {
    null = false
    type = varchar(36)
  }
  column "board_id" {
    null = false
    type = varchar(36)
  }
  column "mode" {
    null = true
    type = varchar(16)
  }
  primary_key {
    columns = [column.workspace_id, column.board_id]
  }
  foreign_key "workspace_board_workspace" {
    columns     = [column.workspace_id]
    ref_columns = [table.workspace.column.id]
    on_delete   = CASCADE
  }
  foreign_key "workspace_board_board" {
    columns     = [column.board_id]
    ref_columns = [table.boards.column.id]
    on_delete   = CASCADE
  }
  check "workspace_board_mode" {
    expr = "`mode` IS NULL OR `mode` IN ('worktree', 'branch')"
  }
}
table "agent" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "name" {
    null = false
    type = varchar(100)
  }
  column "kind" {
    null = false
    type = varchar(32)
  }
  column "user_id" {
    null = true
    type = varchar(36)
  }
  column "proxy_id" {
    null = true
    type = varchar(36)
  }
  column "bin_path" {
    null = true
    type = text
  }
  column "model" {
    null = true
    type = varchar(100)
  }
  column "prompt" {
    null = true
    type = text
  }
  column "settings" {
    null = true
    type = text
  }
  column "created_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  foreign_key "agent_user" {
    columns     = [column.user_id]
    ref_columns = [table.users.column.id]
    on_delete   = SET_NULL
  }
  foreign_key "agent_proxy" {
    columns     = [column.proxy_id]
    ref_columns = [table.proxy.column.id]
    on_delete   = SET_NULL
  }
  index "idx_agent_name" {
    unique  = true
    columns = [column.name]
  }
}
table "deploy_target" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "name" {
    null = false
    type = varchar(100)
  }
  column "ssh_host" {
    null = false
    type = varchar(255)
  }
  column "ssh_user" {
    null = true
    type = varchar(64)
  }
  column "ssh_port" {
    null = true
    type = bigint
  }
  column "ssh_key" {
    null = true
    type = text
  }
  column "base_app" {
    null = true
    type = varchar(100)
  }
  column "base_domain" {
    null = true
    type = varchar(255)
  }
  column "created_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  index "idx_deploy_target_name" {
    unique  = true
    columns = [column.name]
  }
}
table "agent_session" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "card_id" {
    null = true
    type = varchar(36)
  }
  column "board_id" {
    null = true
    type = varchar(36)
  }
  column "agent_kind" {
    null = false
    type = varchar(32)
  }
  column "acp_session_id" {
    null = true
    type = varchar(100)
  }
  column "status" {
    null = false
    type = varchar(24)
  }
  column "cwd" {
    null = true
    type = text
  }
  column "worktree_path" {
    null = true
    type = text
  }
  column "branch" {
    null = true
    type = varchar(255)
  }
  column "started_at" {
    null = false
    type = bigint
  }
  column "finished_at" {
    null = true
    type = bigint
  }
  column "error_text" {
    null = true
    type = text
  }
  primary_key {
    columns = [column.id]
  }
  foreign_key "agent_session_card" {
    columns     = [column.card_id]
    ref_columns = [table.blocks.column.id]
    on_delete   = CASCADE
  }
  foreign_key "agent_session_board" {
    columns     = [column.board_id]
    ref_columns = [table.boards.column.id]
    on_delete   = CASCADE
  }
  index "idx_agent_session_card" {
    columns = [column.card_id, column.started_at]
  }
  check "agent_session_status" {
    expr = "`status` IN ('queued', 'running', 'idle', 'waiting_permission', 'done', 'failed', 'cancelled')"
  }
}
table "session_event" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "session_id" {
    null = false
    type = varchar(36)
  }
  column "kind" {
    null = false
    type = varchar(32)
  }
  column "payload_json" {
    null = true
    type = text
  }
  column "created_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  foreign_key "session_event_session" {
    columns     = [column.session_id]
    ref_columns = [table.agent_session.column.id]
    on_delete   = CASCADE
  }
  index "idx_session_event_session" {
    columns = [column.session_id, column.id]
  }
}
table "conversation" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "card_id" {
    null = true
    type = varchar(36)
  }
  column "board_id" {
    null = true
    type = varchar(36)
  }
  column "node_id" {
    null = false
    type = varchar(64)
  }
  column "column_name" {
    null = true
    type = varchar(200)
  }
  column "title" {
    null = true
    type = text
  }
  column "summary" {
    null = true
    type = text
  }
  column "agent" {
    null = true
    type = varchar(100)
  }
  column "kind" {
    null = true
    type = varchar(32)
  }
  column "workdir_path" {
    null = true
    type = text
  }
  column "cwd" {
    null = true
    type = text
  }
  column "branch" {
    null = true
    type = varchar(255)
  }
  column "started_at" {
    null = false
    type = bigint
  }
  column "ended_at" {
    null = true
    type = bigint
  }
  column "exit_code" {
    null = true
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  foreign_key "conversation_card" {
    columns     = [column.card_id]
    ref_columns = [table.blocks.column.id]
    on_delete   = CASCADE
  }
  foreign_key "conversation_board" {
    columns     = [column.board_id]
    ref_columns = [table.boards.column.id]
    on_delete   = CASCADE
  }
  index "idx_conversation_card" {
    columns = [column.card_id, column.started_at]
  }
  index "idx_conversation_card_node" {
    columns = [column.card_id, column.node_id, column.started_at]
  }
}
table "idempotency" {
  column "token" {
    null = false
    type = varchar(255)
  }
  column "session_id" {
    null = true
    type = varchar(36)
  }
  column "created_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.token]
  }
  index "idx_idempotency_created" {
    columns = [column.created_at]
  }
}
table "flow_state" {
  column "card_id" {
    null = false
    type = varchar(36)
  }
  column "board_id" {
    null = true
    type = varchar(36)
  }
  column "flow" {
    null = false
    type = varchar(200)
  }
  column "node_id" {
    null = false
    type = varchar(64)
  }
  column "branch" {
    null = true
    type = varchar(255)
  }
  column "workdir_path" {
    null = true
    type = text
  }
  column "entered_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.card_id]
  }
  foreign_key "flow_state_card" {
    columns     = [column.card_id]
    ref_columns = [table.blocks.column.id]
    on_delete   = CASCADE
  }
  foreign_key "flow_state_board" {
    columns     = [column.board_id]
    ref_columns = [table.boards.column.id]
    on_delete   = CASCADE
  }
}
table "flow_event" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "card_id" {
    null = false
    type = varchar(36)
  }
  column "flow" {
    null = false
    type = varchar(200)
  }
  column "from_node" {
    null = true
    type = varchar(64)
  }
  column "to_node" {
    null = false
    type = varchar(64)
  }
  column "on_kind" {
    null = false
    type = varchar(32)
  }
  column "detail" {
    null = true
    type = text
  }
  column "said" {
    null = true
    type = text
  }
  column "created_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  foreign_key "flow_event_card" {
    columns     = [column.card_id]
    ref_columns = [table.blocks.column.id]
    on_delete   = CASCADE
  }
  index "idx_flow_event_card" {
    columns = [column.card_id, column.id]
  }
}
table "card_stall" {
  column "card_id" {
    null = false
    type = varchar(36)
  }
  column "node_id" {
    null = true
    type = varchar(64)
  }
  column "kind" {
    null = true
    type = varchar(32)
  }
  column "reason" {
    null = false
    type = text
  }
  column "created_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.card_id]
  }
  foreign_key "card_stall_card" {
    columns     = [column.card_id]
    ref_columns = [table.blocks.column.id]
    on_delete   = CASCADE
  }
}
table "stage_queue" {
  column "card_id" {
    null = false
    type = varchar(36)
  }
  column "board_id" {
    null = true
    type = varchar(36)
  }
  column "column_key" {
    null = false
    type = varchar(128)
  }
  column "flow" {
    null = true
    type = varchar(200)
  }
  column "node_id" {
    null = true
    type = varchar(64)
  }
  column "queued_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.card_id]
  }
  foreign_key "stage_queue_card" {
    columns     = [column.card_id]
    ref_columns = [table.blocks.column.id]
    on_delete   = CASCADE
  }
  foreign_key "stage_queue_board" {
    columns     = [column.board_id]
    ref_columns = [table.boards.column.id]
    on_delete   = CASCADE
  }
  index "idx_stage_queue_column" {
    columns = [column.column_key, column.queued_at]
  }
}
table "board_setup" {
  column "board_id" {
    null = false
    type = varchar(36)
  }
  column "step" {
    null = false
    type = varchar(32)
  }
  column "status" {
    null = false
    type = varchar(16)
  }
  column "changed_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.board_id, column.step]
  }
  foreign_key "board_setup_board" {
    columns     = [column.board_id]
    ref_columns = [table.boards.column.id]
    on_delete   = CASCADE
  }
  check "board_setup_status" {
    expr = "`status` IN ('pending', 'done', 'skipped', 'offered')"
  }
}
table "vcs_seen" {
  column "workspace_id" {
    null = false
    type = varchar(36)
  }
  column "branch" {
    null = false
    type = varchar(255)
  }
  column "kind" {
    null = false
    type = varchar(32)
  }
  column "marker" {
    null = true
    type = varchar(64)
  }
  column "created_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.workspace_id, column.branch, column.kind]
  }
  foreign_key "vcs_seen_workspace" {
    columns     = [column.workspace_id]
    ref_columns = [table.workspace.column.id]
    on_delete   = CASCADE
  }
}
table "checkout" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "workspace_id" {
    null = false
    type = varchar(36)
  }
  column "card_id" {
    null = true
    type = varchar(36)
  }
  column "board_id" {
    null = true
    type = varchar(36)
  }
  column "mode" {
    null = false
    type = varchar(16)
  }
  column "branch" {
    null = true
    type = varchar(255)
  }
  column "path" {
    null = true
    type = text
  }
  column "base" {
    null = true
    type = varchar(255)
  }
  column "created_at" {
    null = false
    type = bigint
  }
  column "released_at" {
    null = true
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  foreign_key "checkout_workspace" {
    columns     = [column.workspace_id]
    ref_columns = [table.workspace.column.id]
    on_delete   = RESTRICT
  }
  foreign_key "checkout_card" {
    columns     = [column.card_id]
    ref_columns = [table.blocks.column.id]
    on_delete   = CASCADE
  }
  foreign_key "checkout_board" {
    columns     = [column.board_id]
    ref_columns = [table.boards.column.id]
    on_delete   = CASCADE
  }
  index "idx_checkout_card" {
    unique  = true
    columns = [column.workspace_id, column.card_id]
  }
  index "idx_checkout_board" {
    unique  = true
    columns = [column.workspace_id, column.board_id]
  }
  index "idx_checkout_live" {
    columns = [column.workspace_id, column.released_at]
  }
  check "checkout_mode" {
    expr = "`mode` IN ('worktree', 'branch', 'plain')"
  }
}
table "source_item" {
  column "source" {
    null = false
    type = varchar(100)
  }
  column "external_id" {
    null = false
    type = varchar(255)
  }
  column "version" {
    null = true
    type = varchar(255)
  }
  column "card_id" {
    null = true
    type = varchar(36)
  }
  column "created_at" {
    null = false
    type = bigint
  }
  column "updated_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.source, column.external_id]
  }
  foreign_key "source_item_card" {
    columns     = [column.card_id]
    ref_columns = [table.blocks.column.id]
    on_delete   = SET_NULL
  }
  index "idx_source_item_card" {
    columns = [column.card_id]
  }
}
table "source_event" {
  column "id" {
    null = false
    type = varchar(36)
  }
  column "source" {
    null = false
    type = varchar(100)
  }
  column "external_id" {
    null = true
    type = varchar(255)
  }
  column "rule" {
    null = true
    type = varchar(100)
  }
  column "outcome" {
    null = false
    type = varchar(16)
  }
  column "card_id" {
    null = true
    type = varchar(36)
  }
  column "detail" {
    null = true
    type = text
  }
  column "created_at" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  foreign_key "source_event_card" {
    columns     = [column.card_id]
    ref_columns = [table.blocks.column.id]
    on_delete   = SET_NULL
  }
  index "idx_source_event_source" {
    columns = [column.source, column.id]
  }
  check "source_event_outcome" {
    expr = "`outcome` IN ('created', 'commented', 'inbox', 'dropped', 'failed', 'skipped')"
  }
}
schema {
}
